### ISSUE TITLE
Do you need temp_wh.dat file after sorting or it can be deleted?

### ISSUE THREAD

**Issue by PhantomSpike** [MouseLand/Kilosort2#101]
Hi,

Many thanks again for developing KS2, really good stuff. It's nice to see that the user community is growing and helping to make KS2 better and better.

Quick question. Do we need to keep the temp_wh.dat file after KS2 is done running? It takes about 1/2 the space of the original file which is quite a lot for big data sets (e.g. 500GB extra on 1TB of data). When running phy, the params.py script uses the original imec.ap.bin file so unless temp_wh.dat is used somewhere behind the scenes while running phy I see no reason to keep it?

@nsteinme 

Thanks!

Alex

**Comment by nsteinme** [comment]
This file is not used in phy - you can safely delete it.

Nick

**Comment by marius10p** [comment]
Issue has become inactive. Closing.
