### ISSUE TITLE
Getting variance from principal component

### ISSUE THREAD

**Issue by markagrios** [MouseLand/Kilosort2#102]
Hi!

I'm trying to use the output from kilosort2 to generate some graphs for a grant and I want to plot the cumulative variance captured versus principle component number. I understand that each principal component explains some percentage of the data but I don't know where that information is stored or how I can generate it from the kilosort2 output. Any help would be appreciated, thanks!!

**Comment by marius10p** [comment]
You mean the variance explained in the waveform, like figure 2 [here](https://papers.nips.cc/paper/6326-fast-and-accurate-spike-sorting-of-high-channel-count-probes-with-kilosort.pdf) ?

**Comment by marius10p** [comment]
Issue has become inactive. Closing.
