### ISSUE TITLE
CUDA_ERROR_ILLEGAL_ADDRESS error

### ISSUE THREAD

**Issue by bapungiri** [MouseLand/Kilosort2#105]
I am seeing the following error on clustering:

System info:
RHEL 7.6
Matlab 2018b
CUDA 9.1
                  
## gpuDevice output in matlab:
Name: 'GeForce GTX 1070'
Index: 1
ComputeCapability: '6.1'
SupportsDouble: 1
DriverVersion: 10
ToolkitVersion: 9.1000
MaxThreadsPerBlock: 1024
MaxShmemPerBlock: 49152
MaxThreadBlockSize: [1024 1024 64]
MaxGridSize: [2.1475e+09 65535 65535]
SIMDWidth: 32
TotalMemory: 8.5136e+09
MultiprocessorCount: 15
ClockRateKHz: 1784500
ComputeMode: 'Default'
GPUOverlapsTransfers: 1
KernelExecutionTimeout: 1
CanMapHostMemory: 1
DeviceSupported: 1
DeviceSelected: 1

## Error 

Time   0s. Determining good channels.. 
found 611 threshold crossings in 54.83 seconds of data 
found 2 bad channels 
Time   6s. Computing whitening matrix.. 
Getting channel whitening matrix... 
Channel-whitening filters computed. 
Time   9s. Loading raw data and applying filters... 
Time 114s. Finished preprocessing 6592 batches. 
Obtained 7 PC waveforms in 1.26 seconds 
time 0.31, pre clustered 1 / 6592 batches 
time 7.26, pre clustered 501 / 6592 batches 
time 14.27, pre clustered 1001 / 6592 batches 
time 21.28, pre clustered 1501 / 6592 batches 
time 28.41, pre clustered 2001 / 6592 batches 
time 35.37, pre clustered 2501 / 6592 batches 
time 42.27, pre clustered 3001 / 6592 batches 
time 49.07, pre clustered 3501 / 6592 batches 
time 55.96, pre clustered 4001 / 6592 batches 
time 62.97, pre clustered 4501 / 6592 batches 
time 69.88, pre clustered 5001 / 6592 batches 
time 76.84, pre clustered 5501 / 6592 batches 
time 83.74, pre clustered 6001 / 6592 batches 
time 90.63, pre clustered 6501 / 6592 batches 
time 0.03, compared 1 / 6592 batches 
time 1.52, compared 501 / 6592 batches 
time 3.01, compared 1001 / 6592 batches 
time 4.49, compared 1501 / 6592 batches 
time 5.96, compared 2001 / 6592 batches 
time 7.45, compared 2501 / 6592 batches 
time 8.92, compared 3001 / 6592 batches 
time 10.45, compared 3501 / 6592 batches 
time 11.94, compared 4001 / 6592 batches 
time 13.41, compared 4501 / 6592 batches 
time 14.89, compared 5001 / 6592 batches 
time 16.37, compared 5501 / 6592 batches 
time 17.85, compared 6001 / 6592 batches 
time 19.35, compared 6501 / 6592 batches 
time 31.36, Re-ordered 6592 batches. 
Time  47s. Optimizing templates ...
Error using gpuArray/sum
An unexpected error occurred trying to launch a kernel. The CUDA error was:
an illegal memory access was encountered

Error in learnAndSolve8b (line 264)
            toc, ibatch, niter, Nfilt, sum(nsp), median(mu), numel(st0), ndrop)

Error in master_kilosort (line 38)
rez = learnAndSolve8b(rez);
  ``

**Comment by etrautmann** [comment]
I've seen this error when I attempt to run two jobs on the same GPU
accidentally. Restarting matlab and launching a single kilosort run should
then work.

**Comment by bapungiri** [comment]
I did restart Matlab and ran the same file again, but I keep getting the same error every time. I tried resizing the ops.NT going from low (128*256+ ops.ntbuff)  to high (128*2048+ ops.ntbuff), but still see the same error.

**Comment by jenniferColonell** [comment]
How many channels do you have in your data? for channel counts less than 16, KS2 may have some trouble with hardcoded values pcs to keep (but there is a fix available).

**Comment by bapungiri** [comment]
I was processing data from 64 channel probe.

**Comment by jenniferColonell** [comment]
Got it. It is a different error then, perhaps related to the size of the data. Has it persisted?

**Comment by bapungiri** [comment]
The data size is >250 GB but I was only trying to sort first hour of data. Next I tried clustering a smaller dataset (~ 2 hr of recording). In both cases I am getting the same error.

**Comment by MarkDTu** [comment]
Hi 

Did you get the issue resolved? I am currently planning on running a similar-sized (64-channel) analysis with a similar gpu (1070). But due to no-one having a gpu at my work, I am waiting on the delivery so I haven't been able to test kilosort 2 out at all.

**Comment by bapungiri** [comment]
No it didn't get resolved yet. I am not sure if changing Matlab and CUDA version will work.

**Comment by bapungiri** [comment]
## Update

I am able to cluster data from 128 channels but for some reasons data from 64 channels isn't still working.
