### ISSUE TITLE
getMeWtW(2) function/filename

### ISSUE THREAD

**Issue by chris7tb** [MouseLand/Kilosort2#108]
Hi.

I realized that 'splitAllClusters' calls 'getMeWtW' and that the function and file name are different. The function name is getMeWtW2 while there exists a different function and file with this name.

I stumbled upon this because i had an out of memory error in getMeWtW. I do not get this error if i use getMeWtW2 instead.

What is the difference between these two, can i use getMeWtW2?

Thanks
Christoph

**Comment by marius10p** [comment]
getMeWtW was just updated by @rajatsaxena to work with large arrays. Thanks for pointing out the file name discrepancy. Unlike getMeWtW2, this one calls a low-level CUDA kernel and runs faster (when it doesn't run out of memory....).

**Comment by marius10p** [comment]
Closed due to lack of activity.
