### ISSUE TITLE
Version of Matlab

### ISSUE THREAD

**Issue by Alkohost** [MouseLand/Kilosort2#112]
Hello.
You wrote in requirements:
Required toolboxes: parallel computing toolbox, signal processing toolbox, MATLAB >=R2016b

But it seems only since version 2017 actions like dataRAW = dataRAW - mean(dataRAW, 1);  are acceptable.

In 2016a is not working.

**Comment by Alkohost** [comment]
Sorry I just found this https://github.com/MouseLand/Kilosort2/issues/74
Can you please note this in the ReadMe?

**Comment by marius10p** [comment]
Thanks for pointing that out. It wouldn't be too difficult to replace all the broadcast instances with the previous Matlab equivalent (bsxfun), but it's probably best to update to a recent Matlab version anyway.

**Comment by marius10p** [comment]
Actually, it says [here](https://blogs.mathworks.com/loren/2016/10/24/matlab-arithmetic-expands-in-r2016b/) that broadcasting should work in 2016b.

**Comment by Alkohost** [comment]
Yes you are right. The limit is between 2016a and 2016b.
So the current description is correct.
