### ISSUE TITLE
Stuck on error: "There is a problem with the graphics driver or with this GPU device. Be sure that you have a supported GPU and that the latest driver is installed."

### ISSUE THREAD

**Issue by hotsoupisgood** [MouseLand/Kilosort2#113]
I'm thinking that my gpu is out-of-date. I successfully installed cuda drivers and ran 'mexGPUall'. I get this error after selecting a data file and probe layout. I have a GTX 650m. 
Is there any way to run kilosort on cpu?

**Comment by marius10p** [comment]
No, sorry. A mobile GPU wouldn't be much good anyway. You can build a decent workstation affordably by following this guide: https://github.com/MouseLand/Kilosort2/wiki/8.-Hardware-guide

**Comment by marius10p** [comment]
Closed due to lack of activity,
