### ISSUE TITLE
template size

### ISSUE THREAD

**Issue by Aegoerd** [MouseLand/Kilosort2#114]
Is there a way to adjust / read the length of the templates (e.g. in samples)? Could adjusting this improve the sort? Thanks for any clue.

**Comment by marius10p** [comment]
That's ops.nt0, which is 61 by default, and it can go up to 81. Unlike feature+clustering-based approaches, the snippet length is not an important factor. In rare cases it might help, if you find that your templates are picking up the spike + some trailing wave.

**Comment by marius10p** [comment]
This issue has become inactive. Closing.
