### ISSUE TITLE
channel maps request

### ISSUE THREAD

**Issue by WeissShahaf** [MouseLand/Kilosort2#117]
is it possible to add the two new Neuropixels 1.0 maps from spikeGLX to kilosort2 default channel maps? Or does anyone have these maps already? 

i'm having trouble converting spikeGLX coordinates and channel mapping to the kilosort format.

checkered pattern (2 column staggered) 
[CheckPattern_3B.zip](https://github.com/MouseLand/Kilosort2/files/3638630/CheckPattern_3B.zip)

long pattern (left sites of bank 0 and right sites of bank 1)
[LongColPattern_3B.zip](https://github.com/MouseLand/Kilosort2/files/3638631/LongColPattern_3B.zip)

**Comment by nsteinme** [comment]
The checkered pattern is there: 1.0 is the same as 3B (sorry for the
confusing terminology) so just choose 3B staggered. For the other one, the
only thing you should need to edit is the y-coords of every other site
(note you can load the channel map files directly, they are in the config
directory, and save a new one with the same variables, but edited).

**Comment by WeissShahaf** [comment]
Are you sure?
the checkered pattern default map "Neuropixels Phase3B1 (staggered)" shows 4 columns, while the 3B2 (aligned) shows 2 columns, as in the neuropixels 1.0 probe layout.

**Comment by nsteinme** [comment]
What are you looking at or referring to when you say 1.0 has "two columns"?
Technically both the staggered and aligned layouts of 3B have two columns
of "pixels" (in the staggered, the location of the recording site within
the pixel is simply flipped to the other side of the pixel, creating what
appears like a 4-column arrangement). The "aligned" 3B design has not been
produced in the production 1.0 probes - they are all the staggered. The 1.0
are just the staggered 3B, then.

**Comment by WeissShahaf** [comment]
in spikeGLX, when recording with default settings. 
probe map looks like there are two aligned columns.
![aligned](https://user-images.githubusercontent.com/45653608/65436023-be546600-de21-11e9-9aa0-3cebd1fc30a4.png)


Bill Karsh has made a custom mapping that takes every other channel to get 7.68mm coverage instead of 3.84mm. it looks staggered
![2](https://user-images.githubusercontent.com/45653608/65436010-b85e8500-de21-11e9-928e-f0906dba1a52.png)
 
this looks very different than the default kilosort P3B1 mapping that you mentioned

**Comment by nsteinme** [comment]
I think Bill just does the display as two aligned columns to make efficient
use of the pixels on your monitor. I think it would make sense to ask him
about that, but I'm sure about the actual site layout on the probe.

Also yes, if I were doing the split bank0/bank1 thing, I would have done it
differently. Looks like Bill has done:
bank0: sites 1, 4, 5, 8, 9, 12, ...
bank1; sites 2, 3, 6, 7, 10, 11, ....
so that he gets a staggered remaining pattern. I would have done:
bank0: sites 1, 3, 5, 7, 9, ...
bank1: sites 2, 4, 6, 8, ...
but of course both are valid. Better check which one you're using.

**Comment by marius10p** [comment]
Closing due to lack of actrivity.
