### ISSUE TITLE
Error loading data 

### ISSUE THREAD

**Issue by MarkDTu** [MouseLand/Kilosort2#121]
Hi

I am having a real issue trying to load data from the buzsaki a64 probes 
![buzsakichannel](https://user-images.githubusercontent.com/35493169/65603239-32ffdf80-df9d-11e9-836e-b0673c2f8bbd.JPG)

I have recorded the data into individual continuous .dat(x64) files at 25000hz and resample before saving into the .bin format at 5000hz for data size (3 hour long recordings)

If I load the .bin file into kilosort2 using the default 16x1 linear mapping I can see traces for the 16 channels and it presumes there are 33 channels

![kilosortimg](https://user-images.githubusercontent.com/35493169/65604571-9f7bde00-df9f-11e9-8330-1a70c579a1b3.JPG)

I have created a channel map for the 64 channel probe but it does not recognise the data

![buzsakikilo](https://user-images.githubusercontent.com/35493169/65604525-883cf080-df9f-11e9-99d7-fb846c797e71.JPG)

I can preprocess the data through the linear 16x1,it starts to spikesort the batches before a 'kilosort cuda error invalid configuration' occurs. I am guessing this is due to the presumed 33 channels instead of the actual 64.

Interestingly I can load the an individual .dat file that is only for one of the 64 channels and it allows it to load the data, but obviously the raw file is a mess as it is only one channel.

![kilosort64](https://user-images.githubusercontent.com/35493169/65604435-68a5c800-df9f-11e9-9734-c7c559b5c797.JPG)

I am using an i5-8500 processor and 1050 gpu, which has been working fine with other data sets.

Any help would be much appreciated

**Comment by nsteinme** [comment]
What is the correct number of channels in the file? The guess of 33
channels is just based on some heuristics but it seems that it was wrong in
this case - you just want to put the correct number into the box and you
should be fine.

I didn't understand what you mean went wrong with your custom channel map,
if you can explain that more I could try to advise.

**Comment by MarkDTu** [comment]
Hi

thanks for getting back.

If I run the analysis on the 64 channel data, with the 16x1 channel layout I can pre-process but when it comes to spike sorting, at around 4 minutes in the following error occurs. 
![matlaberror](https://user-images.githubusercontent.com/35493169/65769991-fbc03880-e12c-11e9-9399-b989aec226bb.JPG)
![kilosort error](https://user-images.githubusercontent.com/35493169/65769999-011d8300-e12d-11e9-99df-8e8671fd4008.JPG)


If I build my own channel layout that is accurate I am unable to even start to preprocess the same data
![channelmap64](https://user-images.githubusercontent.com/35493169/65770107-404bd400-e12d-11e9-9537-c2d534d6cc5c.JPG)

**Comment by marius10p** [comment]
You have to fill in all the parameters, I am not sure why you are not getting the defaults there. 

Be advised that you won't be able to sort anything at 5000Hz. Stick with the 25kHz sampling rate.
