### ISSUE TITLE
first batch spike times are mis-aligned when not starting at zero

### ISSUE THREAD

**Issue by nsteinme** [MouseLand/Kilosort2#124]
In the first batch of the included time range I see spike times shifted by what is probably an "ntbuff"-sized interval (see below). This results in a subset of waveforms appearing to be flat in phy, and I can trace these to just the first two seconds of the included interval. When examining traceview in phy, it's just like in the ksgui: spike times are just off a little bit, and only in the first two sec of the included time interval (i.e. in the first batch). 

In this example trange starts at 77 sec, here's just after that:
![image](https://user-images.githubusercontent.com/7590975/66275643-8d235f00-e83f-11e9-898a-b2778f8cb7ad.png)

And here's a couple seconds later, now aligning:
![image](https://user-images.githubusercontent.com/7590975/66275635-7a108f00-e83f-11e9-92d8-0a4792c042f7.png)

In phy traceview the same thing: the blue waveforms are flat but follow the true spikes by a ms or two: 

![image](https://user-images.githubusercontent.com/7590975/66275653-b17f3b80-e83f-11e9-9242-62af26fbbaf2.png)

Out of the whole unit, only a few of the sample waveforms are incorrectly flat (and by splitting I can track these to the first couple seconds): 
![image](https://user-images.githubusercontent.com/7590975/66275670-d1aefa80-e83f-11e9-9963-d8eb1fa00987.png)

**Comment by marius10p** [comment]
I have never encountered this problem, please let me know if you think it still happens.
