### ISSUE TITLE
Necessity of workstation-grade GPUs?

### ISSUE THREAD

**Issue by Hankslab-ABG** [MouseLand/Kilosort2#127]
Greetings,

My apologies if this has already been answered, but we're building our combination acquistion/kilosort rig for neuropixel data and we had some questions about GPUs. The hardware guide suggests that Nvidia GeForce cards like the RTX 2070 should be sufficient, but are there any advantages to using a quadro GPU or something else with greater ECC memory and floating point precision, or in practice does that not seem to make a difference?

Thanks,

-Adam

**Comment by marius10p** [comment]
No advantage, and you're likely sacrificing speed (a lot) with the quadro card.
