### ISSUE TITLE
about GUI documentation

### ISSUE THREAD

**Issue by ferchaure** [MouseLand/Kilosort2#129]
Hi Marius, just a few questions about the documentation on the wiki that I don't undestand:

1. On the GUI wiki, I don't understand, why it said: one color / another one

> The Probe View (middle) shows the layout of your probe as specified in the channel map. _Green/yellow_ channels are ones selected currently for viewing in the Data View. _Blue/red_ channels are not currently visible in Data View. _Yellow/Red_ channels are excluded from analysis, and do not appear in Data View.

2. On the GUI wiki. How Can I see **traces mode**? I can't read a way to do it

**Comment by nsteinme** [comment]
If you press the 'controls' button you will get a list of commands - use
'c' to switch between traces/colormap mode.

The selected part of the probe is green, or yellow if the channel is in the
selected part but is excluded from the analysis anyway. The unselected part
is blue, or red if the channel is excluded. Hope that helps clarify. I
think if you play around with it you will probably get the idea.
Right-click a channel to include/exclude.

**Comment by ferchaure** [comment]
Thanks!!
