### ISSUE TITLE
Spike amplitude

### ISSUE THREAD

**Issue by CarloCerquetella** [MouseLand/Kilosort2#130]
Hello everyone,

I am using kilosort2 with some strict values in ops.Th ([50 4]) and in ops.lambda ([50 50]) because in this way, if I understood the algorithm correctly, KS2 will pick up only high amplitude spikes and the waveforms assigned to the same template will have the same amplitude (more or less).
I have checked some of them manually and I am still recording some 15microV spikes. I have no clue about the reason why this is still happening. Is there a way to extract the average spike amplitude per template? I check the rez.mu variable but I don't think it is in voltage values but rather related to the template projections. Is it correct?

Thanks for any clue!

**Comment by jaib1** [comment]
Related to this, I'm also wondering how the spike amplitude values returned by kilosort are calculated (presumably based on the templates), given that they don't seem to be uV value corresponding to the binary data file.

**Comment by marius10p** [comment]
Correct, this is about template projections. 50 is extremely high, and I don't know what would happen in that case. Try something like 15 or 20. Even then, some spikes that are small in amplitude will be extracted, because their template projections are high, i.e. they have a lot of distributed information, even though there is no one very large channel. 

If you load it in the most recent version of Phy, it will also calculate raw amplitudes for you and allow you easily switch between them and the Kilosort2 ones. This way you can easily compare.

**Comment by CarloCerquetella** [comment]
Hello, thank you both for the interest and fast answer. In phy the amplitude of this unit is 20 uV then?
![Tet1Unit2Phy](https://user-images.githubusercontent.com/53055810/68379899-15eb2e80-014f-11ea-96d1-a5c1a0515d0f.PNG)
 Ok, I see why I got them even with these high values.
Is the info in uV contained somewhere as a list of values (with the respective position of the template too)?

**Comment by marius10p** [comment]
It's not, that's the template projection. I think the most recent Phy might have deactivated the alternative amplitude views that you could cycle between. Watch this space:  [phy issue](https://github.com/cortex-lab/phy/issues/910) .

**Comment by CarloCerquetella** [comment]
Ok. Thanks a lot!
Do you know how phy calculated these values previously? I would be very happy to write this part in matlab and include it in the kilosort script.

**Comment by marius10p** [comment]
I don't know, but Cyrille usually replies fast, so let's wait for him.

**Comment by marius10p** [comment]
Apparently that was only a problem on my end. You should be able to press "A" and cycle through different types of amplitudes, including the raw.

**Comment by CarloCerquetella** [comment]
Ok, I have downloaded the most recent version of Phy2 and I can actually see the "raw" amplitudes but it says 1000, it can not be in uV:
![photo_2019-11-09_18-52-51](https://user-images.githubusercontent.com/53055810/68532827-78e0ef00-0322-11ea-8110-73f52cdaeadc.jpg)
How does Kilosort2 encode the values in the rez.mu variable? Maybe I could use this info to go back to my original data, no?

**Comment by marius10p** [comment]
I think those are in units of your raw file format. Now you need a conversion factor from that to uV, that you should know from your acquisition system.

**Comment by CarloCerquetella** [comment]
Yes, got it and done.
Thanks a lot!
