### ISSUE TITLE
Channel order in data view in a 2-shank probe

### ISSUE THREAD

**Issue by LJacinto** [MouseLand/Kilosort2#131]
Hi,

I'm using a 64 chan 2 shank probe (2x32 chan). I've used the following parameters for the channel map:

xcoor = [repmat(1,1,32) repmat(251,1,32)]
ycoor = [1:25:25 * 32 1:25:25 * 32]
kcoor = [ones(1,32) repmat(2,1,32)]
chan_map = [1:64] 

When I load a recording file the Probe View looks fine. The waveforms on the Data View also look fine, however, the order of the waveforms (chans) displayed alternates between shanks. This means, instead of displaying all chans on the same shank first and then all the chans on the other shank - as in the original file order (and channel map) - the chans are displayed as alternating between shanks.

On the image below I have de-selected two channels on 1 probe, and you can see the corresponding waveforms (chans) on Data view (red arrows) are alternated with chans from the other shank.

![kilo_alternate](https://user-images.githubusercontent.com/57440649/68293428-d4db1780-0085-11ea-8428-63738f567717.png)

Am I doing something wrong in the chan map? Is this intended, i.e. the chan order is correct but for display purposes chans from different shanks are displayed alternated? Or is there an issue/bug?

Thank you for the help.

Luis

**Comment by nsteinme** [comment]
It just displays traces in order of y-coordinates. You can make the shanks
sequential by shifting the y-coordinates of one of the two shanks up above
the other.

**Comment by LJacinto** [comment]
Thanks. Shifting the y-coords does solve the problem of visualizing the channels in sequential order (including on Phy).
