### ISSUE TITLE
Unrecognized function or variable 'gather_try'

### ISSUE THREAD

**Issue by julieelie** [MouseLand/Kilosort2#132]
Hello,
I'm trying to use kilosort2 for long recordings of 4 tetrodes and while I think I figured out the channel mapping, I'm having a hard time with just getting the whitening to run.
The function gather_try don't seem to be in the Kilosort2 repo.
I found it defined in the rastermap repo though, is that the one Kilosort2 needs?
https://github.com/MouseLand/rastermap/blob/master/matlab/gather_try.m

Are they other repositories that Kilosort2 might depend on and that I should be pulling from github?
Many Thanks!
Julie

**Comment by marius10p** [comment]
My bad, I just updated it. You can just replace it with the Matlab built in "gather".

Where did you find this error, in what script?

**Comment by julieelie** [comment]
This function is called at multiple places in kilosort2 (I did a quick search) but I hit it under computeWhitening.m
But I see it's also called under make-eMouseData_drift.m, make_noise_model.m, predictData.m and ksGUI.m.

Also I'm actually struggling with the channel map.
I tried from the GUI and also with the .m file making sure I got the dimensions of each vector correctly but the map does not show up in the gui when I load my channel map file.
I must be doing something wrong but can't find out what.
Also even when loading the channel map file that definitely contains the sample frequency and the number of channels, the Gui stick with default values (but that is easy to manually change!).
I'm pasting the code I'm using to create my channel map for 4 tetrodes, taking x coordinates and y coordinates in the frontal plane (x: medio-lateral; y: fronto-dorsal). 
Thank you very much for your help!
Best
Julie

function createChannelMapFileTetrode(SubjCoordx, SubjCoordy, OutputPath)
if nargin<3
    OutputPath = 'C:\Users\Dell Workstation\Documents\GitHub\Kilosort2\configFiles';
end
if nargin==0
    % Cooper's coordinates in micrometers
    SubjCoordx = [3600 3200 3200 3600];
    SubjCoordy = [11000 10700 10300 10700];
end
%  create a channel map file for 4 tetrode
Nchannels = 16;
connected = true(Nchannels, 1);
chanMap   = 1:Nchannels; % a row vector)
chanMap0ind = chanMap - 1; % a row vector
xcoords   = repmat([1 2 3 4]', 1, Nchannels/4) + SubjCoordx.*ones(4,1);
xcoords   = xcoords(:); % a column vector
ycoords   = repmat([4 3 2 1]', 1, Nchannels/4) + SubjCoordy.*ones(4,1);
ycoords   = ycoords(:); % a column vector
kcoords   = [1 2 3 4].*ones(Nchannels/4,1); % grouping of channels (i.e. tetrode groups), column vector
kcoords = kcoords(:);

fs = 31250; % sampling frequency of Deuteron
save(fullfile(OutputPath, 'Tetrodex4Co_kilosortChanMap.mat'), ...
    'chanMap','connected', 'xcoords', 'ycoords', 'kcoords', 'chanMap0ind', 'fs')

**Comment by sina253** [comment]
Hi

I've just updated the Kilosort2 and have the same problem:

Unrecognized function or variable 'gather_try'.

Error in computeWhitening (line 90)
    Wrot = whiteningLocal(gather_try(CC), yc, xc, ops.whiteningRange);

Error in ksGUI/computeWhitening (line 770)
            [~,Wrot] = computeWhitening(ops); % this refers to a function outside the gui

Error in ksGUI/updateProbeView (line 1216)
                    obj.computeWhitening()

Error in ksGUI>@(~,~)obj.updateProbeView('reset') (line 271)
                'Callback', @(~,~)obj.updateProbeView('reset'));
 
Error while evaluating UIControl Callback.

**Comment by julieelie** [comment]
Create that little function on your matlab path and you should be good Sina.

function x = gather_try(x)
try
    x = gather(x);
catch
end
end

**Comment by marius10p** [comment]
@sina253 I pushed a fix. 

@julieelie That is just a display issue. For tetrodes, you just want the channels in a tetrode to be very close to each other, and different tetrodes to be very far. The modification below to your code achieve this. The other fields in the GUI should get populated when you load a recording in. 

% Cooper's coordinates in micrometers
SubjCoordx = [3600 3200 3200 3600] - 3200;
SubjCoordy = [11000 10700 10300 10700]-10300;

% create a channel map file for 4 tetrode
Nchannels = 16;
connected = true(Nchannels, 1);
chanMap = 1:Nchannels; % a row vector)
chanMap0ind = chanMap - 1; % a row vector
xcoords = repmat(10*[1 2 1 2]', 1, Nchannels/4) + SubjCoordx.*ones(4,1);
xcoords = xcoords(:); % a column vector
ycoords = repmat(10*[2 2 1 1]', 1, Nchannels/4) + SubjCoordy.*ones(4,1);
ycoords = ycoords(:); % a column vector
kcoords = [1 2 3 4].*ones(Nchannels/4,1); % grouping of channels (i.e. tetrode groups), column vector
kcoords = kcoords(:);

fs = 31250; % sampling frequency of Deuteron

**Comment by julieelie** [comment]
Thank you very very much Marius!

**Comment by marius10p** [comment]
Reopen if necessary.
