### ISSUE TITLE
whitening: No prediction with tetrodes

### ISSUE THREAD

**Issue by julieelie** [MouseLand/Kilosort2#134]
Hello,
I'm using Kilosort 2 to spike sort long recordings (6-8 hours) from 4 tetrodes. I tried different parameters under configFile384.m but cannot find parameters that give me spike prediction in the GUI. I always get flat blue lines no matter what, while I know that there are spikes! It looks like the whitening is somewhat too strong and whipping my spikes. I suspect that the weighted sum of neighbour channels could be too strongly in favor of the channels of the same tetrode and substracting signal. Is there a way to change the weight of the channels for the whitening? Is there a somewhat linear translation between the x,y coordinates entered and the weights in the whitening process?
Thank you for your help!

**Comment by marius10p** [comment]
Can you post a screenshot please of the traces after whitening, as well as the output Kilosort2 produces at the command line?

**Comment by julieelie** [comment]
I don't get anything at the command line at this stage of the data processing (just calling kilosort and loading the data, visualizing them in the gui). The whitening seems to process correctly as I can tell from the log in the gui (you can see that in the screenshots).

Here is a screenshot with raw and filtered traces
![image](https://user-images.githubusercontent.com/8903309/68509495-de9b8100-0225-11ea-9867-4883c837544c.png)



Here with only filtered
![image](https://user-images.githubusercontent.com/8903309/68509517-f3781480-0225-11ea-8924-03363cb9aa46.png)


filtered + prediction
![image](https://user-images.githubusercontent.com/8903309/68509551-0a1e6b80-0226-11ea-8a63-d3eede4a8f13.png)

I was expecting to see at least a few spikes for the prediction, but I can't find anything throughout the time axis.
Thank you!

**Comment by julieelie** [comment]
I got it right!
I found out that the algorithm relies in part on _negative_ threshold crossing, and we have the habit to flip the signs of our recordings in the lab to do _positive_ threshold crossing...
So all is good now! I finally massage my data correctly for Kilosort2.
Thanks!
