### ISSUE TITLE
ks2 returns empty clusters?

### ISSUE THREAD

**Issue by jaib1** [MouseLand/Kilosort2#136]
I've noticed that sometimes ks2 returns empty clusters - e.g. In [this](https://drive.google.com/drive/folders/19sAnF-Mgjv-HKF2H8a0IGePDOuBBoAUn?usp=sharing)
ks2 output directory, clusters 22, 30, and 133 have no spikes, yet they are returned as clusters - how can this be?

**Comment by marius10p** [comment]
It's unusual but it can happen due to the dynamic nature of the spike sorter. Feel free to remove those in a post-processing step.
