### ISSUE TITLE
enable manually remove bad channels?

### ISSUE THREAD

**Issue by babaq** [MouseLand/Kilosort2#139]
Just encounter the situation that some bad channels could be obviously observed when recording, and also when referencing externally, all internal referencing channels are grounded. those channels IDs could be send to KS, so that KS could escape those channels when it start to deciding bad channels, or set them as bad channels anyway after it finished finding bad channels.

I can't find a way to set it right now, and would be trivial to add `ops.badch` and do it in `preprocessDataSub`.

any thought? @marius10p

**Comment by nsteinme** [comment]
Just leave them out of the channel map if you're using the command line
(something like: chanMap = chanMap(~ismember(chanMap, badch));). In the GUI
you can right-click on the channel in either the data view or the probe
view to remove it from analysis.

**Comment by babaq** [comment]
yes, i am using matlab functions, and find the `ops.chanMap` only holding the path to the chanmap files, the loading part and find bad channels are all in the `preprocessDataSub` function. I could try to do a quick pull request, adding lines you suggested.

**Comment by nsteinme** [comment]
You can also load the channel map file and pass that in ops.chanMap, rather
than the path. Then you can remove the bad channels yourself on the
outside. That's the way you should do it.

**Comment by babaq** [comment]
found that `loadChanMap` could handle loaded chanMap.

Thanks

**Comment by babaq** [comment]
is it correct to just set the bad channels in `ops.chanMap.connected` to 0?

**Comment by nsteinme** [comment]
Yep that should also work!

**Comment by babaq** [comment]
ok, I saw that in `preprocessDataSub` the total number of channels in chanmap has a chance to overwrite the `ops.NchanTOT` if it's missing, I am wandering if I removed some bad channels from chanmap, and result in e.g. 269 channels, but the bin file saved all the 384 channels, I should still set `ops.NchanTOT=384`, or I should leave it unset outside , so it will be set automatically in `preprocessDataSub` to 269?

**Comment by marius10p** [comment]
ops.NchanTOT is just the total number of channels in your raw data file. 

ops.Nchan gets set by the algorithm after removing bad channels, and is the total number of sorted channels.

**Comment by babaq** [comment]
Got it, thanks!
