### ISSUE TITLE
error preprocessing at the applying filters step

### ISSUE THREAD

**Issue by LJacinto** [MouseLand/Kilosort2#141]
Hi,

I have been getting this error ("Error preprocessing! Unable to perform assignment because the left and right sides have a different number of elements") in some recordings during the pre-processing stage after the "Loading raw data and applying filters... " step. Image below

![kilosort_error_processing](https://user-images.githubusercontent.com/57440649/68992443-77a04c80-0863-11ea-9460-856a20812a7a.png)

 I know what this error means in Matlab, but have no idea why I'm getting it during this stage. Has anyone experienced this or knows what is going on?

Thank you,

Luis

**Comment by LJacinto** [comment]
Actually, now I am getting this error message for every recording I try to process. Even on the ones I had just processed earlier today withou any error message. However, for some of the error messages the preprocessing finishes and, despite the error message I still get "Finished processing XXX batches"; but for others the preprocessing does not finish after the error message.

Strange.

**Comment by marius10p** [comment]
Most likely, your channel map is not configured correctly. Try running from the scripts to see if the error is reproducible. That might also give you more informative errors. You could also try to set to 0 the min firing rate per channel, in case that is somehow disruptive of your geometry.

**Comment by LJacinto** [comment]
The recording parameters and channels look the same as the ones used in the recordings where I don't get the error - so I'm assuming the channel map should also be same. The only other option I see is if the file is somewhat corrupt.

In any case, I don't get the error with the majority of recordings - so it seems this error is specific to some recordings.
