### ISSUE TITLE
data format for kilosort from plexon pl2 file

### ISSUE THREAD

**Issue by niranjankambi** [MouseLand/Kilosort2#145]
Hi, 
I recently started installed kilosort and started playing with it. I have electrophysiological data recorded as a wide band signal (sampling freq. 40K) from deep brain regions in monkeys using 24-32 contact point laminar probes (Microprobes). 
So following are the steps I followed for preparing the data for kilosort - 
**Converted the pl2 file into mat file using Plexon Matlab SDK function Pl2Ad**
**normalize the data using the maximum value in all recordings and multiplied the resulting data points with 2^16 -1 to convert it into a factor of int16.** 
norm = max(max(max(WideBandData)),abs(min(min(WideBandData))));
kilosortInputData = WideBandData*(2^16-1)/norm;
**Converted the data into int16 format using the function int16()**
datI = int16(LFPdata);
**saved the resulting data into a .bin file**
fid = fopen('C_16Jan2018.bin', 'w');
fwrite(fid,datI,'int16');

Please let me know if the above steps are all kosher.
Thanks in advance,
Niranjan

**Comment by sina253** [comment]
Hi
Our neural data also is in Plexon .plx format.
I converted the data using plx_ad function and it returns the data as raw A/D values. Then you could directly convert the output to int16 by just Matlab int16() function without any additional computation. I don't think any normalization is required.

        for cc=1:length(channels)
            [~, ~, ~, ~, ad(cc,:)] = plx_ad(path\to\plxdata,channels(cc));
        end
        ad = int16(ad);
        fidP = fopen([fname,'.dat'],'w');
        disp('Writing dat file ...');
        fwrite(fidP,ad,'int16');
        fclose(fidP);

**Comment by niranjankambi** [comment]
> Hi
> Our neural data also is in Plexon .plx format.
> I converted the data using plx_ad function and it returns the data as raw A/D values. Then you could directly convert the output to int16 by just Matlab int16() function without any additional computation. I don't think any normalization is required.
> 
> ```
>     for cc=1:length(channels)
>         [~, ~, ~, ~, ad(cc,:)] = plx_ad(path\to\plxdata,channels(cc));
>     end
>     ad = int16(ad);
>     fidP = fopen([fname,'.dat'],'w');
>     disp('Writing dat file ...');
>     fwrite(fidP,ad,'int16');
>     fclose(fidP);
> ```

Hi @sina253 ,
Thanks for your reply. However, I am not sure it works for me as int16 function rounds off all the raw data (which are in the range of -1 to 1 ) to nearest zero or 1. 
For example - 
>> x = [0.2, 0.4, 0.6];
>> y = int16(x)
y =
  1×3 int16 row vector
   0   0   1

**Comment by sina253** [comment]
Hi
If you use 'plx_ad' function to read the Plexon neural data, the output is in raw A/D values and not in volt. The A/D values are integer and their precision are more than when you converting those to volt.

**Comment by niranjankambi** [comment]
Thanks for your clarification. I can't use 'plx_ad' function as I have pl2 files and 'Pl2Ad' functions spits out voltage values and therefore I need to do the above normalization I think.

**Comment by Liu-ChingMing** [comment]
you can use the 'plx_ad' function for the pl2 file.
As what they wrote in their note,
'plx_ad(filename, channel): read all a/d data for the specified channel from a .plx or .pl2 file returns raw a/d values'

I use it, and successfully get the right values.

**Comment by niranjankambi** [comment]
Thanks @Liu-ChingMing as I will try it.

**Comment by mlongR** [comment]
> Hi
> Our neural data also is in Plexon .plx format.
> I converted the data using plx_ad function and it returns the data as raw A/D values. Then you could directly convert the output to int16 by just Matlab int16() function without any additional computation. I don't think any normalization is required.
> 
> ```
>     for cc=1:length(channels)
>         [~, ~, ~, ~, ad(cc,:)] = plx_ad(path\to\plxdata,channels(cc));
>     end
>     ad = int16(ad);
>     fidP = fopen([fname,'.dat'],'w');
>     disp('Writing dat file ...');
>     fwrite(fidP,ad,'int16');
>     fclose(fidP);
> ```

Hi, I'm using the  Plexon system too，but I'm confused that the .plx file seems has not saved the raw data, the "plx_ad" function can only read continue data (raw LFP) that without any spikes.
