### ISSUE TITLE
ErrorMessage: Error using gpuArray/subsasgn Matrix index is out of range for deletion.

### ISSUE THREAD

**Issue by michaellagler** [MouseLand/Kilosort2#15]
Hi,

thank you very much for your great work!

I am just testing kilosort2 on a dataset that I was previously clustering successfully with Kilosort1. Its a 30 min recording with a 2times8 buzsaki probe at 20kHz. I was setting the ChanMap file as for Kilosort1 and also the config file is with default settings except fs.

here is the command out put and also starting to get 2 output figures plotting:

master_kilosort2
Looking for data inside C:\DATA\Kilosort2_test 
Time   0s. Determining good channels.. 
found 25835 threshold crossings in 113.69 seconds of data 
found 0 bad channels 
Time  11s. Computing whitening matrix.. 
Getting channel whitening matrix... 
Channel-whitening filters computed. 
Time  12s. Loading raw data and applying filters... 
Time  16s. Finished preprocessing 70 batches. 
Obtained 7 PC waveforms in 0.37 seconds 
time 0.28, pre clustered 1 / 70 batches 
time 0.09, compared 1 / 70 batches 
time 2.18, Re-ordered 70 batches. 
Time   2s. Optimizing templates ...
2.80 sec, 1 / 142 batches, 3 units, nspks: 0.1469, mu: 10.0000, nst0: 1, merges: 0.1000, 0.0000 
Error using gpuArray/subsasgn
Matrix index is out of range for deletion.

Error in triageTemplates2 (line 7)
W(:,idrop,:) = [];

Error in learnAndSolve8b (line 188)
                triageTemplates2(ops, iW, C2C, W, U, dWU, mu, nsp, ndrop);

Error in master_kilosort2 (line 39)
rez = learnAndSolve8b(rez);

Here, is the error in debug, it seems to complete the first out of 142 batches, but crashed when doing the second;

triageTemplates2 Line 7, W(:,idrop,:) = []; 
W: 61 x 12 x 3 GPU array
idrop: 12 x 12 GPU array

Thank you very much for your help!

Best wishes,
Michael

**Comment by marius10p** [comment]
Can you please double check in the GUI that your channel map configuration is good? Looks like it's not finding spikes in the main optimization.

**Comment by michaellagler** [comment]
Thank you for your answer. Yesterday I was only trying to run Kilosort executing the master file without GUI. Now I just tried the new GUI and it works perfectly using the same ChanMap as I used yesterday when I got the error message above. I cant find any inconsistencies. Is there anything I should specifically check when I run the master file? (paths, config file etc all seem correct)

**Comment by marius10p** [comment]
You also need to change ops.NchanTOT to be the total number of channels in your data file, maybe it's that?

**Comment by michaellagler** [comment]
Thank you. I missed that there is an ops.NchanTOT setting in the master file now. Runs Beautifully !!!
