### ISSUE TITLE
Single spike waveform split 

### ISSUE THREAD

**Issue by NoahDolev** [MouseLand/Kilosort2#151]
Hi, 

We notice that a good percentage of our spikes are actually split up in error. 

![image](https://user-images.githubusercontent.com/45264019/70054832-f249c580-15e0-11ea-96a1-4a86f0ed5394.png)

Any suggestions how to resolve this?

May relate to #29 . 

Thanks,
Noah

**Comment by marius10p** [comment]
This is a consequence of trying to detect small units. You can get rid of this behavior if you increase the threshold sufficiently, but then you will also lose your smaller amplitude units. Alternatively, you can get rid of coincident spikes in post-processing like they do in Methods 8.3 [here](https://www.biorxiv.org/content/10.1101/805010v1.abstract).

**Comment by NoahDolev** [comment]
Hi Marius,

Thanks for your response. I had a look at the article and I also changed the threshold to [20, 8] but I still get many cases that these approaches can't seem to handle. For example:

![sorting_issues](https://user-images.githubusercontent.com/45264019/71322398-d5adf880-24cf-11ea-8517-ea1997a8dc4e.png)


Do you have any suggestions what to do about these? 

Best,
Noah

**Comment by marius10p** [comment]
That seems strange. How often does that happen? I wonder if there is a configuration error in the channel map or the number of channels. Does the data look OK loaded into the Matlab GUI?

**Comment by NoahDolev** [comment]
It looks okay to me in the GUI:

![sorting_issues2](https://user-images.githubusercontent.com/45264019/71323394-2d9e2c80-24db-11ea-89b5-1eff5fa9ab07.png)

WDYT?

**Comment by NoahDolev** [comment]
_Here is another indication:_

![image](https://user-images.githubusercontent.com/45264019/71340936-01c58a00-2561-11ea-9bbf-e04f004ed4d2.png)

You can see the spikes in the surrounding electrodes so it seems like the layout is okay. Unless something happens later in the KS2 pipeline to the layout...

**Comment by dimokaramanlis** [comment]
Maybe your template length (nt0) doesn't match the duration of your spikes? From your phy screenshots, it seems that nt0 is shorter than the spike duration.

**Comment by marius10p** [comment]
That looks like an artifact cluster, not a neuronal cluster. By chance, it has some spike in there.
