### ISSUE TITLE
Kilosort Firing Rate

### ISSUE THREAD

**Issue by chris-weinberger** [MouseLand/Kilosort2#153]
Hi all,

I have a quick question about Kilosort2. What exactly does the firing rate mean in the GUI, and what is its unit? 

I assumed it was spikes/second, but for some reason, it doesn't allow us to input a firing rate >= 1. This is strange because after running the data through Kilosort2 and opening the results in Phy, there is a cluster that has a firing rate of 20. Any details about the firing rate in Kilosort would be greatly appreciated!

Thanks,
Chris W.

**Comment by marius10p** [comment]
Sorry this wasn't clear. The parameter in the Matlab GUI is just the minimum firing rate per  channel, in Hz. Any channel with a firing rate below this value gets discarded before any sorting is done. You can set it to 0 if you want to keep all channels.

**Comment by epmgs97** [comment]
Hi,
About the firing rate view in Phy, I could not find any info about what is plotted. Is it the spikes/ second? Phy let you change de Bin size and number, does it mean that the firing rate is the PSTH?

Thanks
