### ISSUE TITLE
Feature request: Excluding a time range for spikesorting. 

### ISSUE THREAD

**Issue by bapungiri** [MouseLand/Kilosort2#157]
It will be helpful if certain time periods can be excluded from spikesorting. Specially helpful for really long recordings where small unavoidable noisy periods can influence unit isolation/cluster-quality. This will eliminate an added step of creating another binary file excluding those noisy periods. This may also be helpful in excluding other irrelevant epochs for analysis.

**Comment by angelonc** [comment]
You can set `ops.trange = [0 inf];` to include a time range that doesn't include noise. I'm not sure if this is good for indexing multiple periods though?

**Comment by marius10p** [comment]
ops.trange currently only works for a single continuous segment of the recording. We would need to keep track of one time offset per batch, which is doable, but I won't have time to do for a while.
