### ISSUE TITLE
Loading previously sorted results in the GUI?

### ISSUE THREAD

**Issue by angelonc** [MouseLand/Kilosort2#16]
Not sure if this is intended behavior or not: If I sort a recording in the GUI, I can see KS2's prediction and compare to the actual data, which is a nice feature for looking whether/where KS2 is missing spikes. If I have a plotting issue, I can usually exit out of the GUI, restart it, and the same results will load (KS prediction included).

However, if I click the GUI reset button, or exit the GUI, quit Matlab, and open the GUI again, loading that same file from the same working directory (which already includes Kilosort2 results), it no longer shows Kilosort predictions in the GUI, and only gives options to re-preprocess and re-sort the data. I'm curious if this is the intended behavior: it would be nice to be able to reload already sorted results for examination in the GUI without resorting.

**Comment by nsteinme** [comment]
Yeah, agreed. Right now the reset is a hard reset, intended to fix and weird state bugs that might arise, and it deletes the temporary files that allow re-loading a current state. But this would be a great feature, it just requires a bit of work.

**Comment by marius10p** [comment]
I think Phy is meant to be used for this and Phy2 now has way more options that the Matlab GUI. 

Closing from inactivity.
