### ISSUE TITLE
ops.ChanMap redundancy

### ISSUE THREAD

**Issue by JoseGuzman** [MouseLand/Kilosort2#162]
I've just realized that `ops.ChanMap` is defined in both the master file (e.g., **master_kilosort.m**) 

https://github.com/MouseLand/Kilosort2/blob/67a42a87b866b6150385a46eec358adb349d9ff2/master_kilosort.m#L8

and in the configuration file (e.g.,**configFile384.m**) https://github.com/MouseLand/Kilosort2/blob/67a42a87b866b6150385a46eec358adb349d9ff2/configFiles/configFile384.m#L1. 

Is that expected?

**Comment by marius10p** [comment]
Yes. The master_file and configuration file are supposed to be examples, to be modified by the users. As long as it ends up in ops, you can specify options in either of them. For example, the config file might specify your own personal default options, and then you have a separate master_file for every dataset you want to process where you modify those options as needed.
