### ISSUE TITLE
Kilosort2: can't run CUDA_ERROR_ILLEGAL_ADDRESS while running LearnTemplates

### ISSUE THREAD

**Issue by parityviolation** [MouseLand/Kilosort2#163]
mexGPUall seemed to run and complete without a hitch

Here is the error:
image

CUDADevice with properties:

                  Name: 'Quadro P620'
                 Index: 1
     ComputeCapability: '6.1'
        SupportsDouble: 1
         DriverVersion: 10
        ToolkitVersion: 9
    MaxThreadsPerBlock: 1024
      MaxShmemPerBlock: 49152
    MaxThreadBlockSize: [1024 1024 64]
           MaxGridSize: [2.1475e+09 65535 65535]
             SIMDWidth: 32
           TotalMemory: 2.1475e+09
   MultiprocessorCount: 4
          ClockRateKHz: 1354000
           ComputeMode: 'Default'
  GPUOverlapsTransfers: 1
KernelExecutionTimeout: 1
      CanMapHostMemory: 1
       DeviceSupported: 1
        DeviceSelected: 1
ver

MATLAB Version: 9.4.0.813654 (R2018a)
MATLAB License Number: 968398
Operating System: Microsoft Windows 10 Pro Version 10.0 (Build 17763)
Java Version: Java 1.8.0_144-b01 with Oracle Corporation Java HotSpot(TM) 64-Bit Server VM mixed mode

**Comment by marius10p** [comment]
This GPU only has 2GB of memory, which is probably too little even for relatively small datasets.
