### ISSUE TITLE
RE:ACG

### ISSUE THREAD

**Issue by niranjankambi** [MouseLand/Kilosort2#165]
Hi, 
![image](https://user-images.githubusercontent.com/14698586/71648171-8c775900-2cc6-11ea-9994-94dc2f52361d.png)
Can you please let me know what the horizontal line near the abscissa in the ACG plot (e.g shown above) indicate as I did not find any info about it in the manual.
Thanks,
Niranjan

**Comment by marius10p** [comment]
This is a Phy feature so please consult their manual / post an issue there. My guess is that it is the expected ACG from a Poisson process.
