### ISSUE TITLE
How to acquire the sorted spikes info

### ISSUE THREAD

**Issue by ecoluo** [MouseLand/Kilosort2#167]
Hi, Thanks for sharing KS2 and it's useful. But after the sorting, when I want to further use the information of the sorted spikes, I met a problem. **After the modification in phy**, I'm not sure whether the refreshed results are saved in a file called **ksSetting.mat. If so, I found some infomation in this file. I found savDat.rez.st3 includes the time and cluster number of each spike, but I didn't found the exact channel for each spike. 

So, I want to confirm the following questions:
1. Is the ****ksSetting.mat** file what I want?
2. Where can I find the **channel info**?

**Comment by nsteinme** [comment]
ksSetting is a file that the kilosort matlab GUI uses in the background; not intended for analysis, and not modified by phy. After sorting in phy, cluster_group.tsv and spike_clusters.npy are the updated files. Please consult phy documentation and post any further questions about this on the phy github page - thanks!
