### ISSUE TITLE
Identify the same unit from experiments sorted separately

### ISSUE THREAD

**Issue by WaveformDai** [MouseLand/Kilosort2#169]
Hello, everyone from community of KS2,

I have data recorded using linear probe. Due to different lengths of experimental trials, I have to do spike sorting on each experiment separately, even when they are done in succession. 

With two sets of sorted units obtained from each experiment, I have to identify which pair of units are from the same neuron. In other word, I need to determine if unit m from experiment 1 is the same unit as unit n from experiment 2.

My current solution is to calculate the similarity between mean waveforms of any pair of units located on the same electrode('Normalized Euclidean Distance' is the metric used) and check if the value crossed a given threshold. If the recordings are stable, namely, small drift of linear probe, this method works well. However, if the reocrdings were not too stable, or if any experiment is too long, the sorted waveform recorded by the same electrode will always change in shape and amplitude, resulting in bad pairing.

I'd like to know if anyone has experiences in solving such a problem or has any suggestion tackling  'shift of electrode between experiments'. It will be greatly appreciated if any help is provided.

More information related to 'Normalized Euclidean Distance' can be found in following website: https://stats.stackexchange.com/questions/136232/definition-of-normalized-euclidean-distance.

**Comment by Addisonbc** [comment]
Hi, I'm just a user here, not a developer. Would you mind if I ask what's the logistics of having to sort separately because of the different trial lengths?

**Comment by WaveformDai** [comment]
There is a parameter ops.NT, the batch size for saving binary data file and later template fitting, which I set to be equal to the length of an experimental trial. Thus, if the trial lengths for two experiments are different, I have to do spike sorting on each experiment, separately.

Setting ops.NT to trial length maintains trial information and makes data pre-processing and later-readout easier(target data format: Cerebus NSx file). I don't know how others specify ops.NT and makes it possible to do spike sorting on multiple experiments simultaneously regardless of different trial lengths.

**Comment by marius10p** [comment]
ops.NT should only be the length of a batch. This is typically very short (2 sec), so that batches can fit into GPU memory. You should not use ops.NT as the length of your recordings, else most of the functionality of Kilosort2 like drift correction won't make much sense.

If your experiments are done in the same session, then you certainly want to spike sort all the data together, which will take care of matching neurons for you and then you don't have to any more post-processing work of matching neurons.
