### ISSUE TITLE
CUDA error

### ISSUE THREAD

**Issue by Patrick-Mulholland** [MouseLand/Kilosort2#173]
We receive an error when trying to run "mexGPUall" (described below). MATLAB correctly recognizes the Quadro RTX 5000 GPU. I am using MATLAB R2019b and have downloaded VS community 2013, Cuda toolkit 10.1, MATLAB Support for MinGW-w64 C/C++ Compiler, and the GUI layout toolbox. Any suggestions.

When I run 
>>mex -setup C++
MEX configured to use 'MinGW64 Compiler (C++)' for C++ language compilation.

when I run 
>>mexGPUall
Warning: The selected C++ compiler is not supported for CUDA compilation. Searching for a supported compiler. 
> In mexcuda (line 94)
  In mexGPUall (line 5) 
Error using mex
No supported compiler was found. For options, visit https://www.mathworks.com/support/compilers.

Error in mexcuda (line 166)
    [varargout{1:nargout}] = mex(mexArguments{:});

Error in mexGPUall (line 5)
    mexcuda -largeArrayDims mexThSpkPC.cu

The problem is that I don't know why mexGPUall will not run successfully, since I believe I do have the supported compiler.

**Comment by Addisonbc** [comment]
Hey, I'm just a user here, not a developer, but I believe I might have experienced the same problem before. MATLAB R2019b might not support VS 2013. It's a bit too old. You can type `mex -setup -v` in the command window to see the supported compilers.
I think VS 2015 might be acceptable.

**Comment by sbhasin07** [comment]
Hi, I believe that I came across this same issue with MATLAB 2019b and CUDA 10.1. The first problem is, as Addisonbc stated, VS 2013 is too old. Try installing Visual Studio 2019 Community and then running 'mex cpp -setup' and selecting VS 2019. 

The second issue is what I believe to be a bug in MATLAB 2019. Try using this MathWorks-provided workaround (it worked for me). Link to the bug report: https://www.mathworks.com/support/bugreports/2059103

**Comment by Patrick-Mulholland** [comment]
Thanks for your comments. Switching to MATLAB2018b and Cuda toolkit 9.1 fixed the issue. Thanks!
