### ISSUE TITLE
Sudden change of the template over consecutive batches

### ISSUE THREAD

**Issue by Addisonbc** [MouseLand/Kilosort2#175]
Hi, Kilosort community. As I am checking the template changing across time. I've found some pretty unstable templates in the results (it's the dWU template, x axis unit should be 1/40 ms):
![cluster_29_reordered](https://user-images.githubusercontent.com/56739632/72355084-c9732080-36b4-11ea-8ff3-1f94fc1453f3.gif)

![cluster_32](https://user-images.githubusercontent.com/56739632/72356286-04765380-36b7-11ea-9204-f88d287bffed.gif)

The code I used to extract template is this:
```
for iComponent = 1:3
    U{iComponent} = squeeze(rez.UA(:,iCluster,iComponent,iBatch));
    W{iComponent} = squeeze(rez.WA(:,iCluster,iComponent,iBatch));
    template = template + U{iComponent} * W{iComponent}';
end
```
I've tried both with and without reference to `rez.iorig`, and the templates remain unstable either way. And this happens to around 8 clusters out of 45 clusters Kilosort detected. 
I thought the waveform should at least change slowly over the time. Is this something that's expected? Or did I extract the templates wrong somehow?

Thanks for your time!

**Comment by marius10p** [comment]
How long is your recording? The template should always be the average of the last 400 spikes, so it shouldn't be changing that quickly. Would be good to also see the batch-to-batch distance matrix.

**Comment by Addisonbc** [comment]
About 90~120 minutes (4000 batches for this particular session). It's V-probe recording in the NHP brain.
The batch-to-batch distance looks like this:
![distance matrix](https://user-images.githubusercontent.com/56739632/73847743-dc30cf00-47f4-11ea-9a17-9900e257bf56.jpg)
And I also took a look at the `rez.iorig` and it looks like this:
![batch reorder](https://user-images.githubusercontent.com/56739632/73848002-49dcfb00-47f5-11ea-9347-2d24fa353d8e.jpg)
Also I thought `UA` and `WA` should be what was used in the sorting process?
```
rez.WA(:,:,:,k) = gather(W);
rez.UA(:,:,:,k) = gather(U);
rez.muA(:,k) = gather(mu);
```
Thank you for your reply!

**Comment by marius10p** [comment]
I see. When you were plotting it above it was in chronological time order. The batches are re-ordered so that similar time periods are near to each other. You can see that this isolates a few batches that appear to be very different from the rest, presumably because of large movements. You could redo that time-varying plot but index into iorig instead and then it should change smoothly.  

If you want to turn off time-reordering, you can set this option in the config file

     ops.reorder         = 0;

**Comment by marius10p** [comment]
Can you make the figure with reference to iorig? There are a few sharp transitions in your data, so you should expect jumps when you go in chronological order.

**Comment by Addisonbc** [comment]
I thought that was it, but this is after referencing to iorig (`real_batch = rez.iorig(iBatch);`):
![cluster_29_iorig](https://user-images.githubusercontent.com/56739632/74061915-121fb000-49bb-11ea-8c04-728006eea5a4.gif)
Compared to the original (`real_batch = iBatch;`):
![cluster_29](https://user-images.githubusercontent.com/56739632/74062120-8d816180-49bb-11ea-9c7c-a0c1c4029e58.gif)

**Comment by marius10p** [comment]
I am not sure why this happens, but thanks for pointing it out. I'll take a look at it when I next get a chunk of time to develop Kilosort.

**Comment by Addisonbc** [comment]
Thank you very much! And thank you for developing kilosort and making it open-sourced. It was a really educational experience for me reading your paper and code.

**Comment by marius10p** [comment]
The imminent new version of kilosort will no longer do drift tracking, so I am closing this issue.
