### ISSUE TITLE
Can drift correction work with only 5 channels per area?

### ISSUE THREAD

**Issue by adgindrat** [MouseLand/Kilosort2#176]
Hi,
I recorded some monkey data simultaneously from 2*5 electrodes, in 2 distinct brain areas (1 single electrode + 1 tetrode per area).
Will drift correction be correctly performed with only 5 channels per area? Does that make sense to use KS2 with these data? If yes, should I process the 5 channels from one area separately from the 5 channels of the other area or not?
Thanks in advance for your answer.

**Comment by marius10p** [comment]
Yes, it makes sense to use, and yes, you should spike sort together. Kilosort2 employs a tracking model that can follow changes in waveform shape regardless of recording geometry. However, you should judge carefully if the drift is so large that units get lost, in which case you might want to spike sort shorter sections of your experiment separately.

**Comment by adgindrat** [comment]
Thank you! 
I still have problem to design a working probe layout. As far as I got it, xcoords is the horizontal distance between channels, and ycoords is vertical distance between channels, right? What are the units? 
Thanks in advance for your answer.

**Comment by marius10p** [comment]
The units are microns. If some electrodes are far from each other, just put in a relatively large spacing like 200um. The coords are mostly used to determine the order of neighboring channels.
