### ISSUE TITLE
Saving npy files deletes timestamps.npy from open ephys

### ISSUE THREAD

**Issue by tlstevenson** [MouseLand/Kilosort2#177]
The open ephys data format saves two files for continuous recordings: continuous.dat and timestamps.npy. If we save the kilosort results in the same folder as these two files (which is useful so that phy can access continuous.dat), the rezToPhy function will delete the timestamps.npy file. I'm not sure how important that file is, but its probably best that it does not get removed unnecessarily.

**Comment by jsiegle** [comment]
`timestamps.npy` can be recovered from the processor start time (found in `sync_messages.txt`) and the number of samples in `continuous.dat`. However, I agree it would be best not to delete existing .npy files when writing the results.

**Comment by marius10p** [comment]
If anyone wants to make a pull request for deleting only the phy-related npy files, I'll be happy to accept it.

**Comment by TheAnton205** [comment]
Still not fixed; my timestamps file got deleted. I dont understand how to recover it (i need it for spikeinterface library), there is no "sync_messages.txt" file that I can find that @jsiegle mentioned. How can I get my timestamps file back?

**Comment by jsiegle** [comment]
Did you check the directory two levels up from the `continuous.dat` file? There is one `sync_messages.txt` file for each recording, rather than for each stream.

**Comment by TheAnton205** [comment]
Oh my... Did not see that, thank you. I am still not sure about how to re-create the timestamps file. Any advise would be great, sorry if this is a simple question.

**Comment by jsiegle** [comment]
Here's how you could do it in Python:

```python
import numpy as np

num_channels = 384 # the total number of channels in the recording
start_sample = 10201 # the start sample found in sample_numbers.txt

data = np.memmap('continuous.dat', dtype='int16')
total_samples = data.size // num_channels
sample_numbers = np.arange(0, total_samples) + start_sample
np.save('sample_numbers.npy', sample_numbers)
```

Note that this will only generate the local sample numbers for this data stream. To reconstruct `timestamps.npy` containing the global timestamps in seconds, you can recompute the synchronized timestamps offline by following the instructions here: https://github.com/open-ephys/open-ephys-python-tools/tree/main/src/open_ephys/analysis#synchronizing-timestamps

**Comment by TheAnton205** [comment]
Thank you for your quick replies, Josh! The snippet that you sent me worked exactly to get the local sample numbers. In regards to recovering the timestamps.npy file, that link did not make much sense to me. Maybe you can explain why my following solution worked:

Taking a look at a good recording, a timestamps.npy file seems to be just a bunch of -1s? This npy array has the same size and shape as the sample_numbers.npy array. So, after generating that sample_numbers.npy file using the way you described, I was able to simply generate my own timestamps file for that data stream by creating an npy arary of just (-1) in the same size and shape as the sample_numbers one. Seems to work as needed for my spikeinterface uses. 

To my understanding, that link you sent was to create a global timestamps, while I needed a local timestamps for my data stream (LFP for a single recording/experiment). Why are the timestamps all just -1? Did I just read the file wrong or is this true?

Regardless, thank you again for the very quick and thorough responses.

**Comment by jsiegle** [comment]
If your timestamps are all -1, it means that no online synchronization took place, which is totally fine. If you just have one recorded data stream, the local sample numbers are all you need.
