### ISSUE TITLE
Channel Number Changes

### ISSUE THREAD

**Issue by barbouni** [MouseLand/Kilosort2#18]
Hello. 

When running kilosort2 in our raw data we end up getting sorted spikes in less channels than originally recorded from in our actual raw data. We import the channel info in the gui but we only get around 70 from our total of 270 channels. Any ideas why this happens and how we could deal with it?
Thanks!

**Comment by angelonc** [comment]
By default, KiloSort removes "bad" channels that have low spike rates; it could be that a majority of your channels don't have spikes, so are not considered. If this is indeed the problem, you can force it to use all channels by setting ops.minfr_goodchannels to zero. (or the analogous field in the GUI, it's default is .1)

**Comment by barbouni** [comment]
Thank you!

**Comment by angelonc** [comment]
You might also want to make sure your channel map has the correct number of channels, if it is importing fewer into the GUI by default (in the GUI, you should see all channels in the probe layout window, and bad ones will be marked yellow or red)

**Comment by nsteinme** [comment]
I made an issue to remind myself to make this more clear in the GUI: https://github.com/MouseLand/Kilosort2/issues/20

@barbouni if this thread has answered your question, go ahead and close this issue? Thanks -
