### ISSUE TITLE
Error when executing action Next best

### ISSUE THREAD

**Issue by dervinism** [MouseLand/Kilosort2#181]
I keep getting the following error using dev version:
Timeout in _block().
Error when executing action Next best.

**Comment by marius10p** [comment]
I really don't know what this is. More information please?

**Comment by dervinism** [comment]
This happens occasionally when an action takes longer than usual to execute. Not a big issue after all.

**Comment by marius10p** [comment]
Ah, this must be a Phy issue. Please post an issue on Phy if you want @rossant to look into it.
