### ISSUE TITLE
Add a file that contain the official version of kilosort2

### ISSUE THREAD

**Issue by samuelgarcia** [MouseLand/Kilosort2#182]
Dear kilosort and kilosort2 developers,
could it be possible to add a file inside sources like version.txt or even version.m
This file would contains a string with the official version of kilosort2.

Since in spikeforest and spiekinterface we are running some benchmark, tracking the version is really important.

At the moment 
 ```python
spikesorters.print_sorter_version()
 ```
give 
```
herdingspikes: unknown
ironclust: 5.0.8
kilosort: unknown
kilosort2: unknown
klusta: 3.0.16
mountainsort4: unknown
spykingcircus: 0.9.0
tridesclous: 1.4.2
```

If a file inside source would have the version number it would be strithforward to parse and render the version.

Best,

Samuel

**Comment by nsteinme** [comment]
You ought to be able to use a command like this to get the git commit hash: 
`>> [status, hash] = system(sprintf('git -C "%s" rev-parse HEAD', fileparts(which('kilosort'))));`
where `hash` has the string you want, if `status` is not `0`.

Does that work for your purposes?

**Comment by samuelgarcia** [comment]
I was think about using the git hash but a true version linked to a release that user can identify is preferable, no ?
I can do this for now.
