### ISSUE TITLE
Neuropixels channel map with custom selection of channels

### ISSUE THREAD

**Issue by tasteven-ucd** [MouseLand/Kilosort2#183]
I am recording from a Neuropixels probe that has various channels selected along the length of the probe (such as odd channels from 1:383 and even from 384:768), so I created a custom chanMap.mat file based off the selected channels where the chanMap array gives the channel index number for corresponding to each row index of the acquired data (i.e. row 2 of the data corresponds to channel 384). The problem is this does not seem to be the intended use of the chanMap array (I get an indexing issue at ksFilter line 21: `dataRAW = dataRAW(:, ops.chanMap.chanMap)`). So my question is how should i handle this situation? Should the chanMap array simply be 1:384 and then the xcoords and ycoords arrays would contain the appropriate channel locations?

**Comment by marius10p** [comment]
Yes. The only reason to skip an index (i.e. [1 3 4 5...]) is if a channel is dead and you don't want it picked up from the raw data file.

**Comment by marius10p** [comment]
Let me know if you have more questions. Closing for now.
