### ISSUE TITLE
are template features affected by spike overlap?

### ISSUE THREAD

**Issue by tonylien** [MouseLand/Kilosort2#185]
I have a question about the template features (rez.cProj). From the documentation and #82, they are the projection of each spike onto various templates. Are the influence of all other spikes "subtracted" out first? In other words, if there are spikes from multiple templates co-occuring in time (overlapping spikes), does this cause the projection of a spike onto its template to be worse? I'm trying to get some intuition about how the template features could be used to quantify cluster separation and whether spike overlap would distort a spike's projection in template feature space. 

I tried to look at where cProj is computed in the code but it's a little beyond my understanding. Any help is greatly appreciated.

**Comment by marius10p** [comment]
Yes, the influence of other spikes is subtracted out first for these features (but not for the PCA features). 

The main reason we compute template features is to show them in Phy so you can tell if two clusters are well separated or not. See figure 4 in the original [Kilosort](https://www.biorxiv.org/content/10.1101/061481v1) paper for more detail on the maths of these features. Note there is some centering and rescaling going on to make the features more comparable between clusters (see the footnote in the paper).
