### ISSUE TITLE
Common Average Referencing (twice?)

### ISSUE THREAD

**Issue by angelonc** [MouseLand/Kilosort2#19]
Not so much an issue but general question: I noticed that there is an internal option in KS2 to perform CAR on each batch. I'm not sure if this is also the case in KS1, but we typically preprocessed our data with a CAR and high pass filter before passing it to KiloSort. I'm wondering if that is a bad thing to do here, if it is going to subjected to another CAR and high pass filter in KiloSort?

In general, are there consequences to performing a CAR or high pass filter more than once on the same data? From what I gather, all of the thresholds used in KiloSort are not so much based on absolute amplitude, but on some measure of SNR, so I guess I'm wondering if multiple CAR and filtering steps will impact SNR?

Thanks!

**Comment by marius10p** [comment]
I don't think it will matter. I am not sure what order you do it in, but Kilosort does high-pass, then CAR, so the common average can capture the higher contaminating frequencies. This is followed by cross-channel whitening, which further reduces the correlation between channels. If you do high-pass filter and CAR twice in series, that second one probably has minimal impact on the data.

**Comment by angelonc** [comment]
Thanks, I do the preprocessing in the same order. I ran it both ways (skipping our preprocessing), and qualitatively the results look somewhat similar.

**Comment by ChauhanT** [comment]
Hi, sorry to resurrect such an old thread, but I was wondering if, like KS2, KS3 also does a CMR/CAR type step. If so, this will make my preprocessing pipeline much faster.

Also, is this done automatically or does the user have to enforce it? I am dealing with a lot of data atm from a variety of rigs, and am trying to automate away as much as I can without the need for going to the GUI.
