### ISSUE TITLE
same spike, member of two clusters

### ISSUE THREAD

**Issue by SaraMati** [MouseLand/Kilosort2#193]
I've observed sometimes the same spike has been associated to two clusters. 

in the screenshot below, cluster 14 has the same spike as cluster 15. I've attached two screenshots with changing colors for clusters to make it easy to identify the middle spike that is in both clusters.  
also, why cluster 14 has so many flat waves fitted to it? 

I'd be grateful if you help me spot what is wrong here (any config adjustment to avoid this?)

![image](https://user-images.githubusercontent.com/12663563/75731621-1ee3ab00-5cbe-11ea-9b18-d975ca1e217e.png)
![image](https://user-images.githubusercontent.com/12663563/75731974-340d0980-5cbf-11ea-9584-b646e7c8f608.png)

**Comment by SaraMati** [comment]
I would be much grateful if someone addresses the issue of same spikes being sorted into several clusters. I still see the issue, as the picture below in which the 4 spikes shown are sorted into clusters 54, 55, and 49. 

![image](https://user-images.githubusercontent.com/12663563/76782844-44c18300-6787-11ea-96cf-bb3129686fc6.png)

has this issue been discussed anywhere? can you refer me to it?

**Comment by agbondy** [comment]
See the issue thread here: https://github.com/MouseLand/Kilosort2/issues/29

This is a well known issue that is a fairly fundamental consequence of the template matching approach used by Kilosort. The current solution is to remove double-counted spikes in post-processing, for which that thread provides some pointers.

**Comment by SaraMati** [comment]
thank you very much
