### ISSUE TITLE
phy GUI has invisible parts

### ISSUE THREAD

**Issue by HunsonAbadeer1** [MouseLand/Kilosort2#195]
I am trying to vie my kilosort data in the phy GUI, but only the ClusterView and the SimilarityView contain anything. The ClusterScatterView seems o contain invisible information, if I click on it randomly it changes the ClusterView and the SimilarityView. Does anyone have an idea how to solve this.
![Invisible](https://user-images.githubusercontent.com/62069556/76438161-ed07ce00-63ba-11ea-8014-0de025e34c62.PNG)

**Comment by rossant** [comment]
What are your graphics card and graphics driver?
Any error message in the terminal?

**Comment by HunsonAbadeer1** [comment]
There are no error messages when I start it with the anaconda prompt. I tried it with the clear state as well, that didn´t change anything. The Graphics Card is an NVIDIA GeForce RTX 2080 Ti, the driver version is 26.21.14.4166.

**Comment by rossant** [comment]
No error message even if you add the `--debug` option at the end of the phy command?
The system config looks fine...

**Comment by HunsonAbadeer1** [comment]
With the debug command I get a lot of theses:
![Error](https://user-images.githubusercontent.com/62069556/76532109-6fa19380-6476-11ea-9e53-4d5714d835cf.PNG)

**Comment by marius10p** [comment]
This seems like Phy issue, closing. Please open an issue on the phy repository and @rossant can help you there.
