### ISSUE TITLE
Config File Doesn't Load into GUI

### ISSUE THREAD

**Issue by chris-weinberger** [MouseLand/Kilosort2#196]
Hello,

I am currently having an issue getting the GUI to notice changes I make to my config file. Whenever I update the values in the config file, the GUI doesn't load with the new updated values. I'll show what I mean.

Code from kilosort_master.m:
%% you need to change most of the paths in this block

addpath(genpath('C:\Users\chris\Documents\NRTL\Kilosort2-master')) % path to kilosort folder
addpath('D:\GitHub\npy-matlab') % for converting to Phy
rootZ = 'C:\Users\chris\Box\Spike_sorting\ProcessedData\ArtifactRemovedData\7\jdsktestv2-190815-135729'; % the raw data binary file is in this folder
rootH = 'H:\'; % path to temporary binary file (same size as data, should be on fast SSD)
pathToYourConfigFile = 'C:\Users\chris\Documents\NRTL\Kilosort2-master\configFiles'; % take from Github folder and put it somewhere else (together with the master_file)
chanMapFile = '2nd_half_16_channels.mat';

ops.trange = [0 Inf]; % time range to sort
ops.NchanTOT    = 36; % total number of channels in your recording

run(fullfile(pathToYourConfigFile, 'configFile384.m'))
ops.fproc       = fullfile(rootH, 'temp_wh.dat'); % proc file on a fast SSD
ops.chanMap = fullfile(pathToYourConfigFile, chanMapFile);

Code from configFile384.m:
ops.chanMap             = 'C:\Users\chris\Documents\NRTL\Kilosort2-master\configFiles\2nd_half_16_channels.mat';
% ops.chanMap = 1:ops.Nchan; % treated as linear probe if no chanMap file

% sample rate
ops.fs = 24414;  

% frequency for high pass filtering (150)
ops.fshigh = 150; %possibly could be 200 (adjustable)  

% minimum firing rate on a "good" channel (0 to skip)
ops.minfr_goodchannels = 0.1; 

% threshold on projections (like in Kilosort1, can be different for last pass like [10 4])
ops.Th = [10 6];  

% how important is the amplitude penalty (like in Kilosort1, 0 means not used, 10 is average, 50 is a lot) 
ops.lam = 10;  

% splitting a cluster at the end requires at least this much isolation for each sub-cluster (max = 1)
ops.AUCsplit = 0.9; 

% minimum spike rate (Hz), if a cluster falls below this for too long it gets removed
ops.minFR = 1/50;  

% number of samples to average over (annealed from first to second value) 
ops.momentum = [20 400]; 

% spatial constant in um for computing residual variance of spike
ops.sigmaMask = 30; 

% threshold crossings for pre-clustering (in PCA projection space)
ops.ThPre = 8; 

Importantly, I changed ops.Th and ops.fs. However, when I open Kilosort, here is what I see on the GUI:
![defaultmode](https://user-images.githubusercontent.com/29984788/77268634-f7f51500-6c7c-11ea-9bfd-926a9f5c4d59.JPG)

Clearly, this values don't reflect what I have in the config file. I know that I can change these in the GUI, but I'm more concerned about that values in the config file that aren't accessible in the GUI. For example, the frequency for high pass filtering (ops.fshigh) is a parameter I'd like to adjust, but it looks like the updates to my config file aren't making it to the GUI.

I must be missing something, so any help would be greatly appreciated. Thanks!
-Chris

**Comment by nsteinme** [comment]
Hi Chris - the GUI doesn't interface with the config script in any way - so
your observation is the intended behavior. To set those parameters you'll
want to click 'set advanced' and follow the instructions there.

The GUI can be used every time you want to run KS2, but you could also just
use it to work out the correct settings and then transition to using the
script-based mode of running KS2, in which case you would not need the GUI
for anything.

Hth -

**Comment by chris-weinberger** [comment]
Thank you!
