### ISSUE TITLE
170-190 out of 383 channels have low signals...

### ISSUE THREAD

**Issue by Pusm** [MouseLand/Kilosort2#198]
First of all, thank you for developing great software.
Maybe this is not due to kilosort problem, but to my recording quality... so I should apologize to ask here. 
Could you see the attached image '100ms_data_after_CAR'??
110th-240th channels seem to have low voltage than others.

Using Neuropixels 1.0, recordings were made under anesthesia (chlorprothixene 1 mg / kg) from the mouse visual cortex. I recorded from a total of 4 locations with 3.8mm depth (SpikeGLX settings were APx500, LFPx250 , and AP high pass filter 300 Hz. Ground & Reference-soldered External reference was used. External reference was soldered to Ag ball and inserted into cerebellum.)
Using Kilosort2 with the default settings, in three of the four recordings, lump-like 170-190 out of 383 channels were set as bad channels and excluded from analysis. The number of single units (that is,  KSLabel='good') per one recording site is also below 130.
I noticed that by changing minFR from 0.1 to 0, all channels can be analyzed.

However, what I am concerned about is the small number of putative action potentials, below -6SD. (I read your nice matlab code in pre-processing phase)
Possible reasons are maybe below:
-relatively deep anesthesia
-I dont how to distinguish agar vs cortex during recording, so perhaps this low signal channels are in agar?? (Note that I got diffrent bad channels from another recording sites, indicating this problem is not due to probe itself but from mice/agar)
-any structure (maybe thalamus or hippocampus??)  which has low signals
-electrical noise
-broken probe or HS
-something wrong about SpikeGLX or Kilosort2 setting due to my misunderstanding

Screenshots are my rawdata before and after CAR.
I'm a beginner in electrophysiology and don't know if this is noisy. Could you give me any advice?

100ms_data_before_CAR
![100ms_data_before_CAR_plot](https://user-images.githubusercontent.com/23078454/78458934-357f8680-76f0-11ea-80a2-7f37f5ea75cc.png)
![100ms_data_before_CAR](https://user-images.githubusercontent.com/23078454/78458938-39aba400-76f0-11ea-85ce-8af5137c9918.png)
10ms_data_before_CAR
![10ms_data_before_CAR_plot](https://user-images.githubusercontent.com/23078454/78458940-3adcd100-76f0-11ea-9e30-01d46df15de1.png)
![10ms_data_before_CAR](https://user-images.githubusercontent.com/23078454/78458941-3b756780-76f0-11ea-84a3-e6df2f30e93d.png)

100ms_data_after_CAR
![100ms_data_after_CAR](https://user-images.githubusercontent.com/23078454/78459172-2994c400-76f2-11ea-99a0-a7968e389a21.png)
![100ms_data_after_CAR_plot](https://user-images.githubusercontent.com/23078454/78459353-58f80080-76f3-11ea-9f48-bebaadb29bbc.png)
10ms_data_after_CAR
![10ms_data_after_CAR_plot](https://user-images.githubusercontent.com/23078454/78459354-5c8b8780-76f3-11ea-88c9-a791e111ebf3.png)
![10ms_data_after_CAR](https://user-images.githubusercontent.com/23078454/78459168-2568a680-76f2-11ea-9a59-84649038a909.png)
![100ms_data_after_CAR_anothersite](https://user-images.githubusercontent.com/23078454/78459622-3a930480-76f5-11ea-9f49-6e5b86df0db9.png)

another site data after CAR
![10ms_data_after_CAR_plot_anothersite](https://user-images.githubusercontent.com/23078454/78459625-3b2b9b00-76f5-11ea-87ed-8bc7cd520251.png)
![10ms_data_after_CAR_anothersite](https://user-images.githubusercontent.com/23078454/78459627-3bc43180-76f5-11ea-8745-a3bf6591e384.png)
![100ms_data_after_CAR_anothersite](https://user-images.githubusercontent.com/23078454/78459636-58f90000-76f5-11ea-97df-002c4e235ce1.png)

![100ms_data_after_CAR_plot_anothersite](https://user-images.githubusercontent.com/23078454/78459618-3666e700-76f5-11ea-8092-4ac3b390b1b1.png)

**Comment by nsteinme** [comment]
Looks ok to me - In both of your last two plots we can see spikes around
channels 10-20 (i.e. near the top of the plot). Those spikes look good to
me and the data don't appear too noisy. Might just be that there was very
low activity due to the anesthetic (I don't know anything about that
particular anesthetic), or if there was bleeding or too much compression
during insertion. Suggest to look at the kilosort results in phy - assuming
they look ok there too I think you can proceed with analysis, or try more
recordings.

**Comment by Pusm** [comment]
Thank you Nick for replying.
I was very relieved to hear from you who have a lot of experience.
As you told me, I will try to record data this way for a while.
I am very grateful for your altruistic spirit and wish you success :D
