### ISSUE TITLE
Solving **Error in svdecon** when an array is full of NaNs

### ISSUE THREAD

**Issue by JoseGuzman** [MouseLand/Kilosort2#204]
An error in **svdecon** happened to me when using `connected = 0` in the probe file to remove some dead channels (suggested in #139). I was thinking to document how to solve it because issue  #142 was not clear. In my situation, bursts of spikes appear after long periods of total silence (from 10 to 60 seconds).

![phy_screenshot_20200515150028_TraceView](https://user-images.githubusercontent.com/6409964/82118267-54a11780-9776-11ea-8490-c366dba1e022.png)

It returns more or less randomly, the following error to compute the eigenvalues of the matrix C.

```matlab
Error using gpuArray/eig
Input matrix contains NaN or Inf.

Error in svdecon (line 23)
    [U,D] = eig(C);

Error in sortBatches2 (line 11)
[u, s, v] = svdecon(ccb0);

Error in clusterSingleBatches (line 151)
[ccbsort, iorig] = sortBatches2(ccb0);

Error in master_kilosort (line 46)
rez = clusterSingleBatches(rez);
```

For my particular case, C is a 770x770 array full of `NaNs`. I realized that this has been partially addressed by @marius10p  in  https://github.com/MouseLand/Kilosort2/issues/12#issuecomment-469273017. Then setting` ops.reorder =0`; to avoid reordering of batches did the job.

I also changed ops.NT to a larger value (default is 64*1024 ) to increase the size of the batch.
```matlab
ops.NT = 6*32*1024+ ops.ntbuff;  
````
It empirically solved the problem. However, I'd like to know how to relate that number to the size of the batch in real time in the recordings to adjust it better to my silent conditions (10-60 seconds).

**Comment by marius10p** [comment]
ops.NT is the duration of the batch in samples, so it depends on the sampling rate. You can increase that number generously with no penalty loss, as long as you don't run into memory issues. If it's large enough, you may be able to turn the batch reordering back on.
