### ISSUE TITLE
`d_draw` vs  `d_draw64` in MP kernel

### ISSUE THREAD

**Issue by alexmorley** [MouseLand/Kilosort2#208]
https://github.com/MouseLand/Kilosort2/blob/7a03d918c3520ae097be4dc5d48bc90669308189/CUDA/mexMPnu8.cu#L1050-L1053

Hey @jenniferColonell, I may well have misunderstood this but should the above only be run if `ENSURE_DETERM` is unset as we are using single precision `d_draw` in that case? Maybe it doesn't make a difference but want to make sure I understand correctly :)

**Comment by jenniferColonell** [comment]
HI Alexander,

You're absolutely correct, that's a flaw in my logic. Both the conversion of d_draw to double and the conversion back should be dependent on ENSURE_DETERM = 0.

I'll push up that change. Thanks for spotting it, and sorry I failed to catch that case.

jennifer

________________________________
