### ISSUE TITLE
Error using gpuArray/subsref

### ISSUE THREAD

**Issue by cbimbo** [MouseLand/Kilosort2#209]
Hi,
I'm having trouble spikesorting a specific dataset. During the template optimization phase, ks2 keeps crashing at a ~random time, giving the following error:

```
[...]
1186.30 sec, 801 / 2016 batches, 510 units, nspks: 4934.3449, mu: 14.8789, nst0: 4287, merges: 197.0270, 0.4796
Error using gpuArray/subsref
An unexpected error occurred trying to launch a kernel. The CUDA error was:
invalid argument

Error in learnTemplates (line 187)
            W(:,Nfilt + [1:size(dWU0,3)],:) = W0(:,ones(1,size(dWU0,3)),:); % initialize temporal components of waveforms

Error in learnAndSolve8b (line 12)
    rez     = learnTemplates(rez, iorder0);

Error in master_kilosort (line 41)
rez = learnAndSolve8b(rez);
```

When once in debug mode I rerun that specific line "W(:,Nfilt + [1:size(dWU0,3)],:) = W0(:,ones(1,size(dWU0,3)),:);" after the crash it doesn't throw any error, making me suspect some kind of memory overload error occurring once in a while. However, I've been looking at the Windows memory monitoring and it didn't seem to reach a peak when the crash occurs (could be some spike though), and I've already managed to run spikesorting on datasets with a similar or slightly larger size.
I'm working on a ~95GB session and running ks2 with default parameters, a part from the probe template which is custom made (np2.0, 385 channels). The machine I'm using has the following specs:

Processor: Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz (8 CPUs), ~4.2GHz
Memory: 12288MB RAM
Graphics card: NVIDIA GeForce GTX 1060 3GB

Any idea of what could be wrong? Thanks in advance!

**Comment by marius10p** [comment]
This isn't the best computer for spike sorting (see here: https://github.com/MouseLand/Kilosort2/wiki/8.-Hardware-guide). The 1060 with 3GB of RAM is the limiting factor, so you could just upgrade to a card with at least 6GB, ideally 8GB (RTX 2060 or higher). I am not sure the RAM will be sufficient after that, so you might have to get some new RAM too.

**Comment by cbimbo** [comment]
Thanks for the quick reply!
I switched to a computer with bigger RAM and this seems to have solved the issue. I was initially confident with the specs of my computer because I've managed to spikesort bigger datasets, but this specific one might be noisier.
