### ISSUE TITLE
more spikes than Plexon offline sorter

### ISSUE THREAD

**Issue by scally12** [MouseLand/Kilosort2#210]
I am a new Kilosort2 user thus I wanted to compare the outputs with Plexon offline sorted ones (My recording system is TDT, 128 channels system).
I noticed I got usually more spikes than sorted with Plexon offline autosorter. Thus I am wondering whether it is correct due to the sorting method or I did wrong somehow when I use the Kilosort2.
Does anyone know why it could happen like this?
Thanks,

**Comment by marius10p** [comment]
They are very different spike sorting algorithms, so anything is possible. Generally the total number of spikes is influenced by some thresholds, both in the Plexon sorter and in Kilosort, and changing these threshold will change the number of spikes dramatically. You need to look at the results in Phy to see if your units are better isolated, have better refractory periods etc.
