### ISSUE TITLE
having only few good units

### ISSUE THREAD

**Issue by scally12** [MouseLand/Kilosort2#211]
I am wondering whether the geometry of the device is a matter for the sorting method or not. My device is a 128 channel device (from Gray Matter system) - a distance of electrodes is 1500um and XY is horizontal not vertical. If it is not a matter then which parameters I can play with to get more good units?

Thanks

**Comment by marius10p** [comment]
The geometry of the device directly determines what units you can and cannot get. In your case, the electrodes are so far apart that you can only see each neuron on a single channel. Thus, it will be very hard to separate out neurons by their spatial waveforms, and many neurons will look the same when viewed from a single channel. There is nothing the spike sorter can do, other than use the information from single channels as well as possible.
