### ISSUE TITLE
Installation Problems

### ISSUE THREAD

**Issue by tom221085** [MouseLand/Kilosort2#213]
Hi all!
I am currently trying to install Kilosort2 according to the installation guidelines provided in this GitHub repository. I'am using MATLAB 2019b, installed CUDA 10.1 as well as Visual Studio 2013 and 2019. However, everytime I run mexGPUall.m in the CUDA folder I get the following error:

_Warning: The selected C++ compiler is not supported for CUDA compilation. Searching for a supported compiler. 
> In mexcuda (line 94)
  In mexGPUall (line 5) 
Error using mex
No supported compiler was found. For options, visit https://www.mathworks.com/support/compilers.

Error in mexcuda (line 166)
    [varargout{1:nargout}] = mex(mexArguments{:});

Error in mexGPUall (line 5)
    mexcuda -largeArrayDims mexThSpkPC.cu_

Is anyone able to provide help?

Thank you!
Thomas

**Comment by RobertoDF** [comment]
Hi Thomas,
Visual Studio 2013 is not supported by Matlab 2019b, see [here](https://www.mathworks.com/content/dam/mathworks/mathworks-dot-com/support/sysreq/files/system-requirements-release-2019b-supported-compilers.pdf).
While running the installer for Visual Studio 2019, make sure that the "Desktop development with C++" workload is selected!! See [here](https://www.mathworks.com/matlabcentral/answers/443349-how-do-i-install-visual-studio-2017-or-2019-for-use-with-matlab-simulink). That might be why you don't see it as a compiler in Matlab.
