### ISSUE TITLE
cluster_group.tsv re-arrangement

### ISSUE THREAD

**Issue by eduardo-blanco** [MouseLand/Kilosort2#214]
Hi all,

In some of my curated sessions, I noticed that the file cluster_info.tsv is re-arranged or has missed information, while cluster_group.tsv seems correct, overall is not common to occur but I wonder what might be the reason. 

Below I show a comparison of two different sessions, the left one showing the re-arrangement.

![image](https://user-images.githubusercontent.com/13749229/86471102-ff788f80-bd3c-11ea-966f-0ea11fa23a81.png)

What do you think might be the issue?

Thank you for the tools
Eduardo

**Comment by rossant** [comment]
it looks like the program you're using does not load the tsv files properly, no?
Could you copy paste the contents of the files themselves, by loading them in notepad or another text editor?

**Comment by eduardo-blanco** [comment]
Thank you for your fast response:

the output of the looks like this:

id	Amplitude	ContamPct	KSLabel	amp	channel	depth	firing_rate	group	n_spikes	shank
0	74.50000000	100.00000000	mua	4.52919674	65	2320.00000000	8.7 spk/s		23674	0
1	66.20000000	100.00000000	mua	4.62656784	65	2320.00000000	6.3 spk/s		17234	0
2	42.00000000	100.00000000	mua	2.95313883	67	2360.00000000	1.2 spk/s		3207	0
3	113.30000000	100.00000000	mua	7.19309378	71	2440.00000000	9.1 spk/s		24621	0
4	161.80000000	100.00000000	mua	4.53980684	72	2460.00000000	0.8 spk/s		2294	0
5	411.80000000	100.00000000	mua	6.05658054	72	2460.00000000	0.5 spk/s		1279	0
6	47.40000000	100.00000000	mua	2.95211887	76	2540.00000000	6.3 spk/s		17101	0
7	62.60000000	100.00000000	mua	4.37164497	77	2560.00000000	2.1 spk/s		5608	0
8	96.20000000	100.00000000	mua	3.90495682	78	2580.00000000	0.5 spk/s		1402	0
9	39.90000000	100.00000000	mua	2.90963125	80	2620.00000000	1.6 spk/s		4242	0
10	50.70000000	100.00000000	mua	2.69935703	89	2800.00000000	0.8 spk/s		2087	0
11	37.90000000	100.00000000	mua	2.17392397	80	2620.00000000	3.3 spk/s		8853	0
12	168.80000000	100.00000000	mua	4.07830477	83	2680.00000000	1.5 spk/s		3980	0
13	44.30000000	100.00000000	mua	2.94632292	83	2680.00000000	7.1 spk/s		19238	0
14	54.90000000	100.00000000	mua	4.08887815	84	2700.00000000	1.2 spk/s		3370	0
15	66.80000000	100.00000000	mua	4.43079662	84	2700.00000000	1.9 spk/s		5219	0
16	58.50000000	100.00000000	mua	4.08405209	85	2720.00000000	0.9 spk/s		2504	0
17	45.40000000	100.00000000	mua	3.12450027	86	2740.00000000	4.3 spk/s		11811	0
18	69.30000000	100.00000000	mua	4.18443012	91	2840.00000000	2.3 spk/s		6157	0
19	61.40000000	100.00000000	mua	3.21874952	91	2840.00000000	1.8 spk/s		5010	0
20	66.30000000	100.00000000	mua	2.02249146	94	2900.00000000	3.8 spk/s		10375	0
21	70.30000000	100.00000000	mua	4.84725237	107	3160.00000000	1.1 spk/s		2865	0
22	466.40000000	100.00000000	mua	10.65668297	119	3400.00000000	2.1 spk/s		5759	0
23	39.80000000	100.00000000	mua	3.13121080	112	3260.00000000	7.6 spk/s		20677	0
24	264.50000000	100.00000000	mua	5.87457943	114	3300.00000000	0.4 spk/s		1051	0
25	2474.20000000	100.00000000	mua	9.34759617	119	3400.00000000	0.2 spk/s		437	0
26	26.10000000	100.00000000	mua	1.89938211	116	3340.00000000	13.2 spk/s		35795	0
27	41.60000000	100.00000000	mua	2.53896952	127	3560.00000000	16.2 spk/s		44193	0
28	1388.40000000	100.00000000	mua	6.92367792	119	3400.00000000	0.1 spk/s		335	0
29	86.20000000	100.00000000	mua	6.74475622	128	4080.00000000	1.4 spk/s		3791	0
30	79.60000000	3.70000000	good	7.33429098	130	4120.00000000	30.5 spk/s		82997	0
31	130.20000000	3.90000000	good	10.87976742	133	4180.00000000	4.9 spk/s		13279	0
32	78.60000000	100.00000000	mua	6.36459255	133	4180.00000000	3.1 spk/s		8447	0
33	55.20000000	100.00000000	mua	3.92708588	148	4480.00000000	5.7 spk/s		15431	0
34	119.90000000	100.00000000	mua	9.14369202	136	4240.00000000	3.9 spk/s		10598	0
35	114.80000000	100.00000000	mua	7.46712875	135	4220.00000000	2.9 spk/s		7754	0
36	100.60000000	100.00000000	mua	6.92347193	135	4220.00000000	5.4 spk/s		14804	0
37	202.50000000	5.30000000	good	9.42743683	136	4240.00000000	22.7 spk/s		61836	0
39	87.00000000	100.00000000	mua	6.30117607	137	4260.00000000	0.1 spk/s		193	0
40	90.50000000	9.30000000	good	6.86560535	138	4280.00000000	4.4 spk/s		11902	0
41	87.50000000	8.70000000	good	6.74385548	140	4320.00000000	12.7 spk/s		34466	0
42	370.80000000	100.00000000	mua	5.41706181	135	4220.00000000	0.1 spk/s		338	0
43	73.10000000	100.00000000	mua	5.69921637	141	4340.00000000	3.7 spk/s		10103	0
44	193.10000000	0.00000000	good	6.92884350	141	4340.00000000	2.1 spk/s		5723	0
45	296.00000000	0.00000000	good	7.01653910	142	4360.00000000	3.0 spk/s		8238	0
46	99.20000000	2.10000000	good	8.07301807	143	4380.00000000	22.1 spk/s		60078	0
47	83.90000000	100.00000000	mua	6.49300146	147	4460.00000000	15.3 spk/s		41538	0
48	183.20000000	2.70000000	good	7.42848825	148	4480.00000000	5.2 spk/s		14225	0
49	144.00000000	100.00000000	mua	8.89177990	149	4500.00000000	9.2 spk/s		24959	0
50	161.20000000	100.00000000	mua	8.99527836	151	4540.00000000	16.7 spk/s		45455	0
51	115.40000000	100.00000000	mua	8.88544941	152	4560.00000000	6.3 spk/s		17077	0
52	326.20000000	0.00000000	good	11.32279015	153	4580.00000000	6.5 spk/s		17812	0
53	132.70000000	100.00000000	mua	9.25876236	154	4600.00000000	18.5 spk/s		50289	0
54	151.90000000	100.00000000	mua	12.47369957	155	4620.00000000	17.0 spk/s		46204	0
55	113.10000000	100.00000000	mua	8.75651932	155	4620.00000000	10.7 spk/s		29151	0
56	176.30000000	0.00000000	good	8.35138130	157	4660.00000000	4.0 spk/s		10947	0
57	134.20000000	100.00000000	mua	10.30241394	158	4680.00000000	7.6 spk/s		20589	0
58	112.10000000	100.00000000	mua	8.45688629	159	4700.00000000	9.5 spk/s		25725	0
59	110.80000000	100.00000000	mua	5.49339724	160	4720.00000000	0.0 spk/s		56	0
60	129.90000000	100.00000000	mua	8.58007240	159	4700.00000000	12.1 spk/s		33032	0
61	144.20000000	100.00000000	mua	10.74298668	159	4700.00000000	11.8 spk/s		32223	0
62	131.50000000	9.50000000	good	11.35933495	159	4700.00000000	21.9 spk/s		59674	0
63	113.70000000	100.00000000	mua	7.99931383	161	4740.00000000	9.0 spk/s		24360	0
64	123.00000000	100.00000000	mua	7.99841595	162	4760.00000000	9.9 spk/s		26916	0
65	110.70000000	100.00000000	mua	8.71144581	164	4800.00000000	11.2 spk/s		30416	0
66	94.50000000	100.00000000	mua	7.47307348	166	4840.00000000	1.8 spk/s		4788	0
67	139.20000000	100.00000000	mua	10.67665482	166	4840.00000000	9.9 spk/s		26819	0
68	121.60000000	9.70000000	good	8.40779114	166	4840.00000000	10.3 spk/s		28018	0
69	123.00000000	100.00000000	mua	8.61588001	172	4960.00000000	8.0 spk/s		21815	0
70	267.80000000	0.30000000	good	9.80887318	169	4900.00000000	4.2 spk/s		11548	0
71	190.10000000	100.00000000	mua	12.02559662	169	4900.00000000	7.4 spk/s		20193	0
72	150.80000000	100.00000000	mua	10.24229908	171	4940.00000000	11.1 spk/s		30325	0
73	161.80000000	100.00000000	mua	11.95879364	171	4940.00000000	6.5 spk/s		17607	0
74	322.50000000	0.00000000	good	11.44700146	171	4940.00000000	2.3 spk/s		6212	0
75	707.40000000	0.00000000	good	13.53602409	172	4960.00000000	4.2 spk/s		11356	0
76	382.10000000	1.90000000	good	16.37260246	172	4960.00000000	4.0 spk/s		10944	0
77	169.00000000	100.00000000	mua	13.43608761	173	4980.00000000	5.3 spk/s		14458	0
78	211.10000000	100.00000000	mua	14.57031631	173	4980.00000000	0.1 spk/s		264	0
79	284.00000000	5.60000000	good	11.14620018	174	5000.00000000	7.4 spk/s		20091	0
80	241.00000000	100.00000000	mua	16.45082474	183	5180.00000000	13.2 spk/s		35832	0
81	213.00000000	100.00000000	mua	13.28920555	175	5020.00000000	8.7 spk/s		23537	0
82	253.80000000	0.80000000	good	8.02162647	178	5080.00000000	3.9 spk/s		10675	0
83	249.90000000	100.00000000	mua	15.02523708	183	5180.00000000	9.6 spk/s		26118	0
84	264.60000000	100.00000000	mua	6.67835999	180	5120.00000000	0.7 spk/s		1869	0
85	105.90000000	100.00000000	mua	7.45126534	180	5120.00000000	3.8 spk/s		10235	0
87	2148.00000000	100.00000000	mua	10.78480339	183	5180.00000000	0.2 spk/s		410	0
89	54.30000000	100.00000000	mua	4.03477287	172	4960.00000000	7.2 spk/s		19713	0
90	45.20000000	100.00000000	mua	3.23831654	180	5120.00000000	10.4 spk/s		28397	0
91	81.30000000	100.00000000	mua	4.46481943	183	5180.00000000	2.0 spk/s		5356	0
92	413.80000000	100.00000000	mua	4.87126398	192	5860.00000000	0.2 spk/s	noise	493	0
93	249.30000000	100.00000000	mua	4.54650116	192	5860.00000000	0.4 spk/s	noise	1199	0
94	320.20000000	100.00000000	mua	7.88370991	206	6140.00000000	0.2 spk/s	noise	437	0
95	1217.10000000	100.00000000	mua	7.78649998	192	5860.00000000	0.5 spk/s	noise	1453	0
96	358.00000000	100.00000000	mua	3.29744434	193	5880.00000000	0.3 spk/s	noise	813	0
97	165.30000000	100.00000000	mua	5.47222853	219	6400.00000000	0.2 spk/s	noise	667	0
98	94.10000000	100.00000000	mua	2.39517593	114	3300.00000000	2.2 spk/s		5907	0
99	143.50000000	100.00000000	mua	9.64942551	206	6140.00000000	5.6 spk/s	noise	15189	0
100	255.00000000	100.00000000	mua	7.81779289	206	6140.00000000	0.0 spk/s	noise	112	0
101	69.40000000	100.00000000	mua	3.23370028	196	5940.00000000	0.0 spk/s	noise	108	0
102	67.00000000	5.00000000	good	5.07393217	199	6000.00000000	1.2 spk/s	noise	3374	0
103	118.00000000	100.00000000	mua	7.00357246	199	6000.00000000	0.7 spk/s	noise	1906	0
104	137.20000000	0.40000000	good	8.00227356	199	6000.00000000	1.5 spk/s	noise	4195	0
105	99.00000000	0.80000000	good	5.90198898	199	6000.00000000	2.1 spk/s	noise	5806	0
106	194.20000000	100.00000000	mua	5.03984261	199	6000.00000000	0.0 spk/s	noise	107	0
107	171.00000000	100.00000000	mua	8.75585270	199	6000.00000000	18.6 spk/s	noise	50517	0
108	43.50000000	100.00000000	mua	3.09146452	203	6080.00000000	5.2 spk/s	noise	14071	0
109	230.40000000	100.00000000	mua	8.55657768	206	6140.00000000	0.1 spk/s	noise	184	0
110	75.80000000	100.00000000	mua	3.76033926	202	6060.00000000	0.1 spk/s	noise	235	0
111	46.30000000	100.00000000	mua	3.69214129	212	6260.00000000	5.9 spk/s	noise	16077	0
112	160.60000000	100.00000000	mua	10.07580376	206	6140.00000000	5.6 spk/s	noise	15104	0
113	256.10000000	100.00000000	mua	12.20766830	206	6140.00000000	8.3 spk/s	noise	22550	0
114	888.40000000	100.00000000	mua	15.46995926	206	6140.00000000	0.3 spk/s	noise	815	0
115	376.30000000	100.00000000	mua	17.26853943	206	6140.00000000	1.6 spk/s	noise	4349	0
116	1133.30000000	100.00000000	mua	18.61070061	206	6140.00000000	0.8 spk/s	noise	2149	0
117	165.40000000	100.00000000	mua	11.23192692	206	6140.00000000	8.7 spk/s	noise	23554	0
118	145.80000000	100.00000000	mua	3.65886283	206	6140.00000000	0.5 spk/s	noise	1289	0
119	78.40000000	100.00000000	mua	5.16162872	212	6260.00000000	0.1 spk/s	noise	214	0
120	128.00000000	100.00000000	mua	3.69563103	251	7040.00000000	0.1 spk/s	noise	287	0
121	82.20000000	100.00000000	mua	3.62821651	221	6440.00000000	0.9 spk/s	noise	2395	0
122	150.20000000	100.00000000	mua	5.60404825	210	6220.00000000	0.0 spk/s	noise	103	0
123	183.60000000	100.00000000	mua	5.24529696	217	6360.00000000	0.1 spk/s	noise	325	0
124	51.10000000	100.00000000	mua	3.83949041	215	6320.00000000	5.8 spk/s	noise	15823	0
125	157.80000000	100.00000000	mua	6.50575447	217	6360.00000000	0.1 spk/s	noise	144	0
126	481.20000000	100.00000000	mua	5.53674412	215	6320.00000000	0.1 spk/s	noise	361	0
127	111.30000000	100.00000000	mua	3.90140724	199	6000.00000000	1.2 spk/s	noise	3245	0
129	177.80000000	100.00000000	mua	3.54686761	218	6380.00000000	0.2 spk/s	noise	584	0
138	336.10000000	100.00000000	mua	8.31800365	206	6140.00000000	1.8 spk/s	noise	5010	0
139	72.30000000	100.00000000	mua	5.74846840	231	6640.00000000	4.0 spk/s	noise	10897	0
140	2044.20000000	100.00000000	mua	8.18932533	233	6680.00000000	0.1 spk/s	noise	332	0
142	513.50000000	100.00000000	mua	9.77037430	233	6680.00000000	1.0 spk/s	noise	2632	0
144	109.80000000	100.00000000	mua	5.37228584	242	6860.00000000	6.4 spk/s	noise	17316	0
147	153.70000000	100.00000000	mua	4.79176617	227	6560.00000000	0.9 spk/s	noise	2532	0
148	215.20000000	100.00000000	mua	4.90677786	233	6680.00000000	0.7 spk/s	noise	1828	0
149	83.40000000	100.00000000	mua	5.30410099	252	7060.00000000	11.5 spk/s	noise	31361	0
151	461.40000000	100.00000000	mua	4.71191311	233	6680.00000000	0.2 spk/s	noise	631	0
152	111.70000000	100.00000000	mua	4.37951279	77	2560.00000000	0.9 spk/s		2428	0
153	475.30000000	100.00000000	mua	4.49096727	78	2580.00000000	0.1 spk/s		376	0
154	230.90000000	100.00000000	mua	3.80724359	81	2640.00000000	0.1 spk/s		286	0
155	167.20000000	100.00000000	mua	10.59670067	89	2800.00000000	4.5 spk/s		12210	0
156	680.80000000	100.00000000	mua	5.17419147	84	2700.00000000	0.2 spk/s		428	0
157	184.50000000	100.00000000	mua	4.40794563	89	2800.00000000	0.5 spk/s		1463	0
158	120.50000000	100.00000000	mua	4.18592978	85	2720.00000000	0.2 spk/s		624	0
159	150.90000000	100.00000000	mua	4.28067875	91	2840.00000000	0.5 spk/s		1389	0
160	50.40000000	0.00000000	good	4.91184092	107	3160.00000000	2.1 spk/s		5792	0
161	193.70000000	4.40000000	good	11.79333496	119	3400.00000000	10.2 spk/s		27687	0
162	1055.90000000	100.00000000	mua	11.63196564	119	3400.00000000	0.2 spk/s		568	0
163	543.80000000	100.00000000	mua	7.37204742	119	3400.00000000	0.4 spk/s		1167	0
164	525.00000000	100.00000000	mua	6.09475613	116	3340.00000000	0.2 spk/s		525	0
165	182.40000000	100.00000000	mua	7.38122416	135	4220.00000000	2.1 spk/s		5616	0
166	1521.30000000	100.00000000	mua	6.33255053	135	4220.00000000	0.2 spk/s		588	0
167	117.70000000	100.00000000	mua	9.23097610	149	4500.00000000	7.1 spk/s		19420	0
168	152.40000000	100.00000000	mua	12.09588814	169	4900.00000000	0.6 spk/s		1594	0
169	287.10000000	100.00000000	mua	16.36822128	172	4960.00000000	12.4 spk/s		33770	0
170	247.90000000	100.00000000	mua	14.11677074	174	5000.00000000	3.9 spk/s		10676	0
171	552.20000000	100.00000000	mua	14.81251144	174	5000.00000000	1.9 spk/s		5054	0
172	309.00000000	100.00000000	mua	13.23150539	176	5040.00000000	7.2 spk/s		19562	0
173	411.50000000	100.00000000	mua	8.35261631	177	5060.00000000	2.0 spk/s		5414	0
174	125.70000000	2.90000000	good	7.77153540	183	5180.00000000	15.2 spk/s		41463	0
175	282.60000000	100.00000000	mua	7.15953541	183	5180.00000000	0.7 spk/s		1888	0
176	96.60000000	100.00000000	mua	4.58886862	192	5860.00000000	1.1 spk/s	noise	3029	0
177	165.50000000	2.50000000	good	12.24347782	202	6060.00000000	34.6 spk/s	noise	94224	0
178	312.20000000	100.00000000	mua	4.33193779	220	6420.00000000	0.2 spk/s	noise	453	0
179	231.90000000	100.00000000	mua	17.08504486	206	6140.00000000	2.9 spk/s	noise	7838	0
180	55.10000000	100.00000000	mua	3.28854871	209	6200.00000000	0.1 spk/s	noise	174	0
181	107.20000000	100.00000000	mua	7.09947300	231	6640.00000000	3.8 spk/s	noise	10380	0
182	793.50000000	100.00000000	mua	17.48976517	233	6680.00000000	1.4 spk/s	noise	3876	0
186	190.40000000	100.00000000	mua	11.90426350	233	6680.00000000	2.7 spk/s	noise	7215	0
187	804.50000000	100.00000000	mua	9.51361847	226	6540.00000000	0.7 spk/s	noise	1884	0
188	345.80000000	100.00000000	mua	12.28863811	233	6680.00000000	0.6 spk/s	noise	1704	0
189	76.20000000	100.00000000	mua	3.41927838	84	2700.00000000	0.5 spk/s		1367	0
190	48.10000000	100.00000000	mua	3.56238341	193	5880.00000000	0.0 spk/s	noise	111	0
191	2308.10000000	100.00000000	mua	17.75636292	233	6680.00000000	0.3 spk/s	noise	743	0
192	1974.40000000	100.00000000	mua	17.74783325	233	6680.00000000	0.1 spk/s	noise	368	0
193	804.40000000	100.00000000	mua	10.22878361	233	6680.00000000	0.3 spk/s	noise	804	0
194	2104.50000000	100.00000000	mua	15.28512383	206	6140.00000000	0.1 spk/s	noise	379	0
195	1232.30000000	100.00000000	mua	5.31948853	84	2700.00000000	0.1 spk/s		311	0
197				3.60263872	218	6380.00000000	0.3 spk/s	noise	924	0
198				3.60263872	218	6380.00000000	5.1 spk/s	noise	13789	0
199				3.60263872	218	6380.00000000	2.1 spk/s	noise	5715	0
201				15.01002598	222	6460.00000000	0.3 spk/s	noise	701	0
204				20.44759369	222	6460.00000000	29.8 spk/s	mua	81147	0
205				20.44759369	222	6460.00000000	0.5 spk/s	noise	1405	0
206				15.01002598	222	6460.00000000	15.3 spk/s	mua	41628	0
207				15.01002598	222	6460.00000000	0.1 spk/s	noise	232	0
208				9.60119438	223	6480.00000000	13.5 spk/s	good	36836	0
209				9.60119438	223	6480.00000000	0.2 spk/s	noise	527	0
211				9.69544315	223	6480.00000000	0.0 spk/s	noise	104	0
212				9.69544315	223	6480.00000000	6.8 spk/s	good	18539	0
213				9.69544315	223	6480.00000000	0.0 spk/s	noise	28	0
215				18.11770821	224	6500.00000000	0.2 spk/s	noise	589	0
217				7.44077396	224	6500.00000000	0.1 spk/s	noise	167	0
219				16.99105453	224	6500.00000000	0.0 spk/s	noise	126	0
222				7.44077396	224	6500.00000000	0.0 spk/s	noise	130	0
223				16.99105453	224	6500.00000000	3.6 spk/s	mua	9862	0
224				16.99105453	224	6500.00000000	0.0 spk/s	noise	21	0
226	226.30000000	100.00000000	mua	18.13373566	224	6500.00000000	0.0 spk/s	noise	53	0
228				7.44077396	224	6500.00000000	0.0 spk/s	noise	17	0
229				18.11770821	224	6500.00000000	13.3 spk/s	mua	36099	0
230				18.11770821	224	6500.00000000	0.0 spk/s	noise	130	0
231	226.30000000	100.00000000	mua	18.13373566	224	6500.00000000	1.4 spk/s	mua	3704	0
232	226.30000000	100.00000000	mua	18.13373566	224	6500.00000000	0.1 spk/s	noise	265	0
234				7.44077396	224	6500.00000000	0.0 spk/s	noise	2	0
236				7.44077396	224	6500.00000000	3.5 spk/s	noise	9580	0
237				7.44077396	224	6500.00000000	2.1 spk/s	noise	5655	0
238	112.20000000	100.00000000	mua	8.92309284	225	6520.00000000	14.1 spk/s	noise	38466	0
239	112.20000000	100.00000000	mua	8.92309284	225	6520.00000000	0.5 spk/s	noise	1280	0
240	77.60000000	100.00000000	mua	5.73003960	228	6580.00000000	11.8 spk/s	noise	32213	0
241	77.60000000	100.00000000	mua	5.73003960	228	6580.00000000	0.7 spk/s	noise	1947	0
243	154.50000000	100.00000000	mua	6.21410608	231	6640.00000000	0.2 spk/s	noise	634	0
244	154.50000000	100.00000000	mua	6.21410608	231	6640.00000000	4.8 spk/s	noise	13065	0
245	154.50000000	100.00000000	mua	6.21410608	231	6640.00000000	0.4 spk/s	noise	988	0
247	194.60000000	100.00000000	mua	11.52586460	233	6680.00000000	0.3 spk/s	noise	732	0
248	106.00000000	100.00000000	mua	8.03458595	233	6680.00000000	10.0 spk/s	noise	27199	0
249	106.00000000	100.00000000	mua	8.03458595	233	6680.00000000	0.4 spk/s	noise	1220	0
250	194.60000000	100.00000000	mua	11.52586460	233	6680.00000000	9.3 spk/s	noise	25185	0
251	194.60000000	100.00000000	mua	11.52586460	233	6680.00000000	0.1 spk/s	noise	375	0
252	227.40000000	1.10000000	good	17.56162643	233	6680.00000000	20.8 spk/s	noise	56573	0
253	227.40000000	1.10000000	good	17.56162643	233	6680.00000000	0.5 spk/s	noise	1315	0
255	55.10000000	3.70000000	good	3.93136215	243	6880.00000000	0.1 spk/s	noise	212	0
256	55.10000000	3.70000000	good	3.93136215	243	6880.00000000	3.6 spk/s	noise	9713	0
257	55.10000000	3.70000000	good	3.93136215	243	6880.00000000	2.1 spk/s	noise	5583	0
258	92.60000000	100.00000000	mua	5.90647364	247	6960.00000000	8.5 spk/s	noise	23040	0
259	92.60000000	100.00000000	mua	5.90647364	247	6960.00000000	0.2 spk/s	noise	624	0

The function that I use to read the file is from the function readClusterGroupsCSV:

fid = fopen(filename);
C = textscan(fid, '%s%s');
fclose(fid);

I should comment for clarification than only a subset of the cells had been curated but that is the same case for all my sessions and only a few of them (5 out of 52) will show the issue.

**Comment by rossant** [comment]
this file looks correct. I suppose the readClusterGroupsCSV only works on cluster_groups.tsv and not cluster_info.tsv which is a special file created by phy and that exports the entire contents of the cluster view. It is typically not expected to be read unless you want to do your own analysis, independently of KS2 and phy

**Comment by eduardo-blanco** [comment]
I see I was not aware. These recordings have several probes and I used "info.tvs" mainly for getting the channel were KS identify the cluster to focus only on shanks were there is manual curation but I detect the inconsistency in few files. So better would be to add the channel as an output as you indicated in the plugin examples: https://phy.readthedocs.io/en/latest/plugins/.

I will try that then.
Thanks a lot for the help
Eduardo

**Comment by eduardo-blanco** [comment]
As an alternative, I loaded info.tsv using the following specs for textscan:

fid = fopen(filename);
C = textscan(fid, '%s%s%s%s%s%s%s%s%s%s%s','Whitespace','','TreatAsEmpty','','Delimiter','\t');
fclose(fid);

(taken from https://de.mathworks.com/matlabcentral/answers/157803-whitespace-problem-with-textscan#comment_241588) 

Now I can access all info. I cross-checked with the output from group.tsv, and at least in my dataset, there is no mismatch.

Thanks for a lot for orient me
Eduardo

**Comment by Coglet00** [comment]
my clusterview doesnt show up in phy and i cant find the function readClusterGroupsCSV. is this part of phy ?
