### ISSUE TITLE
MATLAB Compiler Runtime Package

### ISSUE THREAD

**Issue by jpellman** [MouseLand/Kilosort2#215]
Hello Kilosort World,

I apologize if this is addressed elsewhere, but I was unable to find a similar issue in the Kilosort2 issue tracker.  I would like to know if there are any plans to distribute a compiled version of Kilosort2 built using the [MATLAB Compiler](https://www.mathworks.com/products/compiler.html) that can be distributed independently of a full-fledged copy of MATLAB and run with the [MATLAB Compiler Runtime](https://www.mathworks.com/products/compiler/matlab-runtime.html).  I know of at least one other neuroscience software package that uses this distribution scheme ([SPM](https://en.wikibooks.org/wiki/SPM/Standalone)) and it's very useful for labs that don't want to purchase a full copy of MATLAB.  It also would allow you to install Kilosort2 on a cluster without dealing with the added complication of MATLAB licensing, which can help out folks who like to use ad-hoc cluster tools like [Starcluster](http://star.mit.edu/cluster/).

**Comment by nsteinme** [comment]
We talked about it (agree with your comments about the advantages) but we
thought compiling the GPU code is likely to be a challenge. If you can try
to compile it and get it working (plus document the steps so it can be
re-compiled by us or others as necessary) that would be very helpful!

**Comment by jpellman** [comment]
Neither I nor my group currently have a setup readily available that is configured with all the prerequisites to attempt an MCR binary, but we should have such a setup in the near future.  When we do I'll see if I can take a stab at this.

**Comment by yqushair** [comment]
Hello! I was also running into issues compiling the code and then came across this thread. Just wanted to confirm two things:

1. As it stands, there is no way to use Kilosort without owning a Matlab license, and
2. There are plans to release Kilosort4 soon, which is implemented in Python

If these are correct, is there an estimated release date for KS4? Thanks and take care!
