### ISSUE TITLE
Artifacts are biasing the sorting

### ISSUE THREAD

**Issue by yagui** [MouseLand/Kilosort2#217]
Hi,

I have movement artifacts that usually are not a big problem, because even with artifacts kilosort is able to find good units.
But for some dataset it seems that this artifacts greatly bias the kilosort algorithm and it prevents kilosort to find good units. In some cases this is a low percentage of spikes, but for some other cases is all artifact an almost no spikes.
This is an example of the latter case, all the cluster created from kilosort are highlighted in colors and in the raw signal you can see a lot of spikes that where not assigned to any cluster.
![phy_screenshot_20200505083322_TraceView](https://user-images.githubusercontent.com/4296015/81067032-110ff900-8eac-11ea-99e9-b6f815e7415e.png)
![phy_screenshot_20200505083301_TraceView](https://user-images.githubusercontent.com/4296015/81067037-12d9bc80-8eac-11ea-87b5-9d3951194c26.png)
![phy_screenshot_20200505083248_TraceView](https://user-images.githubusercontent.com/4296015/81067044-14a38000-8eac-11ea-88f0-703b72c7c70f.png)
This movement artifacts are ramdon so I don't have a known time to remove them.
I was also thinking to have a threshold and remove anything that goes above the threshold.
I was wondering if there is a particular set options that would help to ignore this artifact and make kilosort able to catch the good units.

_Originally posted by @yagui in https://github.com/MouseLand/Kilosort2/issues/202#issuecomment-624038636_

**Comment by jess-breda** [comment]
Also run into this issue, but our data is much noisier & still struggling. You can try pre-processing the data by creating a binary mask of amplitudes above a threshold, and zeroing out anything above that threshold. Should help

**Comment by JoseGuzman** [comment]
I also found that setting `ops.criterionNoiseChannels ` between 0.01 (1%) and up to 0.2 (20%) helps. It allows selecting a percentage of templates that span more channels, thereby capturing noise across all channels. Check Issue #202

**Comment by marius10p** [comment]
Yes, I think you should preprocess out those artefacts. Everyone's artifacts can be a little different (or a lot), so we don't yet have a common artifact detection step in the pipeline. Perhaps at some point we will add something inside the GUI so you can quickly check how well it works. Until then, I am closing this issue.
