### ISSUE TITLE
Spiketime alignment in Kilosort2

### ISSUE THREAD

**Issue by manimoh** [MouseLand/Kilosort2#221]
Hi,

I wanted to know what are the 'spiketimes' in the Kilosort2 results correspond to in the spike waveform. Traditional manual spike sorting on (input inverted) threshold-ed data would always yield the positive peaks of the waveform as spiketimes, but it wasn't very clear to me if that is the case in Kilosort2 since it uses a completely different approach.

I went through the github issues and [this](https://github.com/MouseLand/Kilosort2/issues/137#issuecomment-558217721) pointed me to the fact that it could be either the positive or negative peak. 
I would love some clarification in this.

Thanks!

**Comment by manimoh** [comment]
I should have probably mentioned why I was seeking clarification on this. I wanted to compare Kilosort2 results to manually spike sorting results using [spikecomparison](https://github.com/SpikeInterface/spikecomparison). This compares the spike trains from both the methods and computes an agreement score between the manually sorted units and the KS2 units. However if the spiketimes correspond to different features of the waveform, then these comparisons are not ideal. Thus I wanted to find out what part of a spike waveform (peak, valley, something else?) is referred to as the spiketime.

**Comment by marius10p** [comment]
It should approximately be the max abs, which can either be the peak or the valley depending on what kinds of spikes you are looking at.
