### ISSUE TITLE
mexGPUall error, unable to read mexw64

### ISSUE THREAD

**Issue by raettchen** [MouseLand/Kilosort2#224]
I get the following error by running mexGPUall.
```
Error using mex
Unable to read '...\spikedetector3.mexw64'. Change file permission to readable.
Error in mexcuda (line 166)
    [varargout{1:nargout}] = mex(mexArguments{:});

Error in mexGPUall (line 7)
    mexcuda -largeArrayDims spikedetector3.cu
```

Here is my environment:

- MATLAB R2019a
- Windows 10
- RTX 2080 (CUDA 10.1.0 driver)
- Microsoft Visual C++ 2017 as C++ compiler (using `mex -setup C++`)
- Installed CUDA toolkit version 10.0
- Installed MinGW-w64

Do you have any suggested solution?
Thank you very much.

**Comment by marius10p** [comment]
It looks like you're on the data shift branch. We only support the master branch until that branch gets merged in.

**Comment by raettchen** [comment]
Thank you for reply. You are right, I was on the data shift branch. I am now on the main branch, but I get a similar but slightly different error.
```
Building with 'NVIDIA CUDA Compiler'.
Error using mex
Unable to read '...\Kilosort2\CUDA\mexThSpkPC.mexw64'. Change file permission to readable.

Error in mexcuda (line 166)
    [varargout{1:nargout}] = mex(mexArguments{:});

Error in mexGPUall (line 7)
    mexcuda -largeArrayDims mexThSpkPC.cu
```

**Comment by marius10p** [comment]
Hmm, can you try to run Matlab as administrator and see if this still happens? Otherwise, install Kilosort2 in a different place where you have file permissions.

**Comment by raettchen** [comment]
Great, running MATLAB as administrator worked! Afterwards, I could successfully run kilosort either as administrator or not. Thank you very much.
