### ISSUE TITLE
Channel sites not accurate in Phy

### ISSUE THREAD

**Issue by AamnaLawrence** [MouseLand/Kilosort2#225]
Hi,

After using KS2 for sorting my data, I obtain the unit activities for each of the clusters and then compute the firing rate. I want to know which cluster belongs to what channel and I was relying on Phy for it. However, the firing rate computed by Phy for my cluster of interest is different from what I calculated.  Is there a way I can find the exact channel sites for the clusters?

**Comment by JoseGuzman** [comment]
In the [Phy documentation](https://phy.readthedocs.io/en/latest/sorting_user_guide/) you can read that **spike_times.npy** contains the times (in sampling points) ordered from small to big of all units. In **spike_clusters.npy** you will have the cluster ID (integers) that correspond to these spikes. For example, the first element of  **spike_clusters.npy** the ID of the first unit in your cluster.

In Python, you would use something like this to get all the spikes form that first cluster:

```python
# read *npy binaries, let path be the location of your sorting (e.g. $HOME/binaries/Nobelprize/TC001/kilosorting/)
spike_times = np.load(path + 'spike_times.npy').flatten()
spike_clusters = np.load(path + 'spike_clusters.npy')

myid = spike_clusters[0] # first unit
spike_times[np.where(spike_clusters==myid)]
```
If you divide the length of by the size of the recording by the size of your recording (in sec.) you can get the average firing rate of your Unit. You will see that Phy returns a *similar* value (with 2 decimal points accuracy, though)

**Comment by AamnaLawrence** [comment]
Thank you!
