### ISSUE TITLE
(GUI) No constructor 'handle.listener' with matching signature found.

### ISSUE THREAD

**Issue by alejoe91** [MouseLand/Kilosort2#23]
Hi,

I'm trying to launch the GUI after installing the GUI Layout Toolbox and I get this error:
```
No constructor 'handle.listener' with matching signature found.

Error in uiextras.Container (line 95)
            obj.Listeners{end+1,1} = handle.listener( containerObj, findprop( containerObj, 'PixelBounds' ),
            'PropertyPostSet', @obj.onResized );

Error in uiextras.Box (line 38)
            obj@uiextras.Container( varargin{:} );

Error in uiextras.VBox (line 44)
            obj@uiextras.Box( varargin{:} );

Error in ksGUI/build (line 100)
            obj.H.root = uiextras.VBox('Parent', f,...

Error in ksGUI (line 47)
            obj.build(parent);

Error in kilosort (line 17)
h = ksGUI(f);
```

Apparently, the issue is recent (https://se.mathworks.com/matlabcentral/fileexchange/47982-gui-layout-toolbox - see comment from 7 Mar 2019). I'm using Matlab 2018b on Ubuntu 18.04.

Any workaround?

Thanks,
Alessio

**Comment by nsteinme** [comment]
I think someone else had this issue and the problem was that they had installed the wrong version of the gui layout toolbox. The version at your link is the correct one, but maybe you should uninstall and re-install from that link? It's working for me on 2018b (though I am on win10).

**Comment by etrautmann** [comment]
I ran into this issue and it was as Nick described. Installing the newer
version of the toolbox solved it for me.

**Comment by alejoe91** [comment]
I will try to install from the link and let you know the outcome.

Thanks again!
Alessio

**Comment by alejoe91** [comment]
Installing the downloaded toolbox solves the problem. Thanks

**Comment by Datamance** [comment]
I have GUI Layout toolbox 2.3.5 on R2022b and I'm getting this error, FWIW. Have there been more recent updates to GUI Layout Toolbox that have broken things?

**Comment by Datamance** [comment]
Nevermind, that particular issue is fixed after restarting MATLAB. Go figure!
