### ISSUE TITLE
Python version

### ISSUE THREAD

**Issue by Dradeliomecus** [MouseLand/Kilosort2#230]
Hi,

I saw at https://github.com/MouseLand/Kilosort2/wiki/8.-Hardware-guide that you have an "imminent release of the Python version".

I know that with the current situation things might have been prosponed, but can we expect kilosort2 to run solely on python in 2020?
What are the news about that?

Thank you

**Comment by marius10p** [comment]
Yes, we can expect that. We are now trying to make sure the results are the
same between matlab and python, and adding a data registration step to both
the matlab and python versions.

**Comment by Dradeliomecus** [comment]
Thanks! That is great news.

If it is in the testing stage, do you think it would be possible to have access to the code (since we do not have matlab)?
We could help test to see if it runs fine on our dataset.

Cheers

**Comment by marius10p** [comment]
The code is public [here](https://github.com/rossant/pykilosort) but we know it doesn't work, so not much point testing it.
