### ISSUE TITLE
learnAndSolve8b (line 332) - Error using gpuArray/subsref Index exceeds matrix dimension.

### ISSUE THREAD

**Issue by JBauto** [MouseLand/Kilosort2#24]
Hi,

I'm trying to get Kilosort2 to working using the classic method of scripts. For the chanMap, I'm using the same as in Kilosort1 and the config file with the new changes.

I'm running Kilosort2 as a compiled binary since it's meant to be executed in a cluster. It shouldn't be a problem since it worked fine with Kilosort1.

Here is the output of the crash,

ops = 
struct with fields:
chanMap: 'neuropixPhase3A_kilosortChanMap.mat'
fbinary: '/tmp/myRun_g4_t0.imec.ap.bin'
datatype: 'bin'
NchanTOT: 385
fproc: 'temp_wh.dat'
fs: 30000
fshigh: 150
minfr_goodchannels: 0.1000
Th: [10 4]
lam: 10
AUCsplit: 0.9000
minFR: 0.0200
momentum: [20 400]
sigmaMask: 30
ThPre: 8
spkTh: -6
GPU: 1
nfilt_factor: 4
ntbuff: 64
NT: 65600
whiteningRange: 32
nSkipCov: 25
scaleproc: 200
nPCs: 3
useRAM: 0
trange: [0 Inf]

Time   0s. Determining good channels.. 
found 19227 threshold crossings in 29.04 seconds of data 
found 55 bad channels 
Time   6s. Computing whitening matrix.. 
Getting channel whitening matrix... 
Channel-whitening filters computed. 
Time  48s. Loading raw data and applying filters... 
Time  51s. Finished preprocessing 14 batches. 
Obtained 7 PC waveforms in 0.79 seconds 
time 0.93, pre clustered 1 / 14 batches 
time 0.21, compared 1 / 14 batches 
time 4.91, Re-ordered 14 batches. 
Time   5s. Optimizing templates ...
6.86 sec, 1 / 30 batches, 57 units, nspks: 7.9294, mu: 16.7608, nst0: 110, merges: 0.0000, 0.0000 
memorized middle timepoint 
reverted back to middle timepoint 
Elapsed time is 10.237392 seconds.

ntot =

        9252

Error using gpuArray/subsref
Index exceeds matrix dimension.

Error in learnAndSolve8b (line 332)

Error in kilosort_main (line 78)

parallel:array:SubsrefSubscriptExceedsDim

Any idea on what's causing the error?
Thanks!

**Comment by marius10p** [comment]
Hi, this likely looks like a configuration problem. Did you change NTOT? 

We highly recommend starting with the GUI to make sure your data is seen correctly by Kilosort2. The GUI runs the same code, it just allows to see the formatted and pre processed data.

**Comment by JBauto** [comment]
I just grabbed the StandardConfig_MOVEME.m file and added the fbinary,  fproc and set NchanTOT to 385. 

Running using the GUI with the same binary file and setting probe layout to neuropixPhase3A, it detects automatically 385 and, running everything in the default settings, it crashes in the same place. Preprocessing runs fine and crashes mid Spikesorting.

![kilosort2](https://user-images.githubusercontent.com/7757542/54044601-47c68280-41c7-11e9-9a7a-b368c9bc66a6.png)

Let me know if you need anything else. Thanks!!

**Comment by marius10p** [comment]
Is this on Neuropixels phase 3A data? Do you have the extra 385th channel? I cannot see the data in the data viewer, (there should be spikes there) so something is not working correctly on the configuration side. What software did you use for acquisition? It also looks like a very short recording (28 seconds), is that what you were trying to run?

**Comment by JBauto** [comment]
Yes, its Neuropixels phase 3A data and we have the extra channel. It's sample file that we use to verify if the compilation process went ok and it served us well with Kilosort1. Using a standard acquisition with Kilosort2 everything runs fine.

I guess we can close this issue. Thanks for the help!
