### ISSUE TITLE
Adjusting FS (Sampling Frequency) from GUI

### ISSUE THREAD

**Issue by alex-attinger** [MouseLand/Kilosort2#30]
Thanks a lot for this great tool. It worked 'out of the box' for us for Neuropixel data. However we encountered the following issue when using it with a different probe with different sampling rate.
When running the Kilosort2 from the GUI, it looks like it always uses the default sampling frequency (30'000), at least the field rez.ops.fs is set to 30000, even when in the GUI, a different sampling rate is set. It seems to work when starting kilosort via the master_kilosort.m and adjusting the ops.fs parameter in the config file.

**Comment by dimokaramanlis** [comment]
I had the same issue, so I ended up only using the master file.

**Comment by marius10p** [comment]
Issue has become inactive. Closing.
