### ISSUE TITLE
Strange templates for non neuropixel data

### ISSUE THREAD

**Issue by alex-attinger** [MouseLand/Kilosort2#31]
When using Kilosort2 for data acquired with a Neuralynx probe, the extracted templates often do not match the mean waveforms, like in the attached examples. (I pulled these examples from within template-gui from phy) This does not seem to be the case when using Kilosort1 on the same data (or using Kilosort2 on Neuropixel data). Any idea what could cause this?
![waveform_68](https://user-images.githubusercontent.com/2227711/54398047-d9296f00-4675-11e9-8d09-5818bf83702e.png)

![waveform_24](https://user-images.githubusercontent.com/2227711/54397937-7637d800-4675-11e9-8560-3cac4047be69.png)

**Comment by marius10p** [comment]
Have you verified that this data is seen correctly in the Matlab GUI? 

The templates look fine, the mean waveforms are strange so maybe there is also something off in the timing.

**Comment by alex-attinger** [comment]
Thank you for your reply. There might have been a timing issue, which is fixed now.Data looks good in the GUI (see below; but still sorting via the script due to sampling frequency). 
![image](https://user-images.githubusercontent.com/2227711/54467281-48b86080-4741-11e9-8fe9-8934e1f5b6fa.png)

 I think the issue is slightly better and most cells look fine. I am still trying to understand why some might look like this:

![image](https://user-images.githubusercontent.com/2227711/54467364-e0b64a00-4741-11e9-89b9-12b0f738aef8.png)

Is this a potential issue or is it ok if a few units look like this?

**Comment by marius10p** [comment]
That looks close to the noise floor. The data is high pass filtered and channel whitened, which changes waveforms to different extent depending on their spatio temporal spectrum. We might add more steps to reject low amplitude stuff like that.
