### ISSUE TITLE
Unit channel not accurate

### ISSUE THREAD

**Issue by Bassir** [MouseLand/Kilosort2#32]
When I run kilosort using the following channel map for our [Cambridge P series](https://www.cambridgeneurotech.com/silicon-probes) (2 shank) probe,

```
Channel map = [21 29 17 27 19 30 18 24 32 31 20 22 23 25 26 28 11 3 15 5 13 4 16 10 2 1 14 12 9 7 8 6]
X coordinates = [1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 3 2 3 2 3 2 3 2 3 2 3 2 3 2 3 2]
Y coordinates = [1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16]
K coordinates = [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
```

While I see some good waveforms, the cluserview "best channel" shows channels with little to no amplitude. It's completely off. Could this be an issue with how my channel map is configured? Any advice on how to properly map this 2-shank 32-channel probe? I feel like the geometry of the channels is accurately portrayed by the "probe view" cartoon, but the results don't make much sense with respect to which channels are best and the depth seems to be off too.

**Comment by marius10p** [comment]
Something is likely off. Have you tried running the Matlab GUI to see if your data is loaded in correctly?

**Comment by Bassir** [comment]
> Something is likely off. Have you tried running the Matlab GUI to see if your data is loaded in correctly?

The data looks good in the gui as far as raw tracings are concerned. I managed to have the "depth" be accurate by putting a negative sign in front of the Y coordinates, but the channel is still wrong.

<a href="http://i.imgur.com/bq4cVX3.png">
  <img src="http://imgur.com/bq4cVX3l.png" />
</a>

**Comment by marius10p** [comment]
I meant the Matlab GUI, not the Phy GUI. It's easier to debug configuration problems in the Matlab GUI, see [here}(https://github.com/MouseLand/Kilosort2/wiki/1.-The-GUI).

**Comment by Bassir** [comment]
> I meant the Matlab GUI, not the Phy GUI. It's easier to debug configuration problems in the Matlab GUI, see [here](https://github.com/MouseLand/Kilosort2/wiki/1.-The-GUI).

The Matlab GUI shows reasonable raw tracings and the probe view looks appropriate.

**Comment by marius10p** [comment]
Microns, and it is in fact used by one step in the algorithm. 

Ok, Your screenshot shows that the largest channels have spikes and features. Do you mean the channel identities are not reported correctly?

**Comment by Bassir** [comment]
> Microns, and it is in fact used by one step in the algorithm.
> 
> Ok, Your screenshot shows that the largest channels have spikes and features. Do you mean the channel identities are not reported correctly?

For example in the screenshot above,  looking at unit ID 34, it lists the "channel" as 23 which if you look in WaveFormView, channel 23 is completely flat and channel 9 in fact has the largest amplitude.

**Comment by Bassir** [comment]
Channel listed in clusterview is actually the index of the channel, not the specific channel identity from the channel map. This is not an issue with kilosort, but with how phy displays results.

**Comment by Dakshitha-BA** [comment]
I am facing the same issue with channel IDs displayed in Phy. Isn't the displayed channel number in Phy the channel with the peak waveform amplitude?

**Comment by rossant** [comment]
@Dakshitha-BA could you update to the latest development version of phy and phylib, and see if that fixes it? This version supports the `show_mapped_channels = True|False` parameter in params.py to show the original or channel-mapped ID in phy

**Comment by Dakshitha-BA** [comment]
Thanks for the quick response. Updating phy and phylib fixed the issue.
