### ISSUE TITLE
rezToPhy `clusterIDs` are not assigned

### ISSUE THREAD

**Issue by babaq** [MouseLand/Kilosort2#36]
Hi,

when I do `[spikeTimes, clusterIDs, amplitudes, templates, templateFeatures, ...
    templateFeatureInds, pcFeatures, pcFeatureInds]=rezToPhy(rez, rootdir);` matlab error said it's not assigned, and indeed in `rezToPhy` function.

it seems the `spike_clusters.npy` is saved but not reflected in the `clusterIDs` variable in line 107.

If my guess is correct, the `clusterIDs` is meant to have the same meaning of `spike_cluster.npy`, then it could be easily fixed.

**Comment by marius10p** [comment]
Not sure what that function is supposed to return, but if you want to use the clustering results in Matlab, you are better served by the rez structure. I think I forgot to document these outputs, I'll do that soon.

**Comment by marius10p** [comment]
Actually, nvm, it's in the wiki: https://github.com/MouseLand/Kilosort2/wiki/7.-Output-variables

**Comment by nsteinme** [comment]
Sorry yes those return arguments were a deprecated old idea. As Marius says, just use rez directly, or if you discarded rez then you can load data with this function which has similar output to that list of return arguments: https://github.com/cortex-lab/spikes/blob/master/preprocessing/phyHelpers/loadKSdir.m

Fixed via: Removed the return arguments from the function https://github.com/MouseLand/Kilosort2/commit/e7740f6de9bc55b471521d37ac991eee483a5a19

**Comment by babaq** [comment]
thanks for point out the functions to read `Phy` exported data, but i am wandering if someone just need the `spikeStruct` that the `loadKSdir` returns without `Phy` workaround, it's the best place within the `rezToPhy` to return this `spikeStruct`.

**Comment by babaq** [comment]
yeah, I guess it's better letting `rezToPhy` to do just converting job, and write another function to extract similar data from `rez`. 
But the similar data have already been extracted in `rezToPhy`, so I thought why not return it out. it's fairly Straightforward, I could make a pull request if you permit.

**Comment by nsteinme** [comment]
Well that was the original logic of having those return arguments, but I
think at this point it is better to leave rezToPhy alone since it is a core
component of the pipeline. Logically speaking, it has a separate function.
Thanks -

**Comment by babaq** [comment]
ok, I got it, thanks
