### ISSUE TITLE
kslabel good in Phy

### ISSUE THREAD

**Issue by kevinbolding** [MouseLand/Kilosort2#38]
The quoted documentation below makes it appear that when KS2 is done and results are saved using the Kilosort GUI, the 'good' units should be labeled as such when the results are opened in Phy. I installed yesterday (March 22, 2019) in Windows 10, according to the Phy install instructions and I am not seeing any labeling. I have found the cluster_KSlabel.tsv and can interpret this in MATLAB, but am not certain how to inform Phy about it's existence. Is this not fully implemented yet or am I missing something in my setup or data management?

> Kilosort2 automatically sets the "good" units in Phy based on a <20% estimated contamination rate with spikes from other neurons (computed from the refractory period violations relative to expected).

**Comment by marius10p** [comment]
Did you install the development version of Phy? There should be some stats in the cluster list, including whether KS2 thought it was "good"/

**Comment by kevinbolding** [comment]
I believe that I have installed the development version, I am attaching evidence thereof.
![phydevelopinstall](https://user-images.githubusercontent.com/9322812/54884053-ae43d580-4e42-11e9-9b0d-225eaa84bbad.PNG)


I'm not certain what else would be diagnostic, so I've attached a view of template-gui upon opening and a view of the folder contents for the recording. 
![templateguiopeningview](https://user-images.githubusercontent.com/9322812/54884054-b6037a00-4e42-11e9-862f-0814c7d74d33.PNG)
![phytestfoldercontents](https://user-images.githubusercontent.com/9322812/54884055-b69c1080-4e42-11e9-8b0e-03da3391fec3.PNG)

**Comment by marius10p** [comment]
The full command is in the main phy readme at https://github.com/kwikteam/phy. 

> activate phy
> pip install git+https://github.com/kwikteam/phy git+https://github.com/kwikteam/phy-contrib --upgrade

I think what you are missing is the clone of the latest phy repository. I don't think you need to run "python setup.py develop", maybe these are some older instructions?

**Comment by kevinbolding** [comment]
Solved (by running this exact command)! Thank you!
