### ISSUE TITLE
neuropixPhase3A_kilosortChanMap_385 coordinates lost due to size mismatch

### ISSUE THREAD

**Issue by aliddell** [MouseLand/Kilosort2#4]
If you try to use neuropixPhase3A_kilosortChanMap_385.mat as committed for your chanMap, you'll [lose your probe geometry](https://github.com/MouseLand/Kilosort2/blob/master/preProcess/loadChanMap.m#L46) (xc/yc) early on in the sorting, since `chanMap` has 385 elements where `xcoords` and `ycoords` each have 384.

**Comment by marius10p** [comment]
Removed the unnecessary file.
