### ISSUE TITLE
CUDA ERROR Illegal Address

### ISSUE THREAD

**Issue by NoahDolev** [MouseLand/Kilosort2#40]
Hi,

I have tried to run kilosort2 on Ubuntu 16.04, CUDA 9.0, G++ 7.3 using a V100 and on WIN10, CUDA 9.0, MSVS2013 using a 1060. In both machines, I get the following crash:
```{Matlab}
Error using mexSVDsmall2
An unexpected error occurred during CUDA execution. The CUDA error was:
CUDA_ERROR_ILLEGAL_ADDRESS

Error in learnAndSolve8b (line 141)
    [W, U, mu] = mexSVDsmall2(Params, dWU, W, iC-1, iW-1, Ka, Kb);
```
Any ideas?

Best,
Noah

**Comment by marius10p** [comment]
Is the Win10 configuration the same one we talked about before? Has it run on any dataset successfully? Might be good to set it up on the "eMouse" simulation, to figure out if it's the dataset+config or the machine.

**Comment by NoahDolev** [comment]
Hi,

Indeed, the same setup. I'll try the eMouse simulation. Thanks for your help.

Best,
Noah

**Comment by NoahDolev** [comment]
Hi,

Indeed the eMouse simulation completes successfully. Still, ideally, our spikes would cause an interpretable error rather than a CUDA crash. When I figure it out, I'll post the solution here. 

Cheers,
Noah

**Comment by NoahDolev** [comment]
Hi,

I managed to get past this error by shrinking the batch size significantly. Not sure why that's causing an error. I ran this on a V100 with 32GB of RAM and I am sorting a short recording (~1 min) but anyway for now that works.

Now I run into an indexing error when dropping units. I'll post that as a separate issue. 

Best,
Noah

**Comment by veronikasamborska1994** [comment]
Hi, 

I am having the same problem. Kilosort2 was doing just fine yesterday but today I started getting this error and I get it even if I try running it on the same data as I already sorted yesterday so it must be something to do with the machine. I am using cuda 8.0 on a Matlab 2017a on Ubuntu 16.04.5 LTS. 
Woud appreciate if you have any advice on how to fix this. 

Thanks! 
Veronika

Error using mexSVDsmall2
An unexpected error occurred during CUDA execution. The CUDA error was:
CUDA_ERROR_ILLEGAL_ADDRESS

Error in learnAndSolve8b (line 142)
    [W, U, mu] = mexSVDsmall2(Params, dWU, W, iC-1, iW-1, Ka, Kb);

**Comment by veronikasamborska1994** [comment]
For anyone experiencing a similar error, I think it has something to do with the recordings not having many cells/spikes. I get this error only on recordings in CA1 on days that I marked as not having many cells online as I was probably not in the cell layer yet. Kilosort1 still works in these cases though.
