### ISSUE TITLE
Max number of filters per channel?

### ISSUE THREAD

**Issue by angelonc** [MouseLand/Kilosort2#42]
I'm trying to figure out what the ops.nfilt_factor parameter does. It seems like it tries to limit the number of clusters assigned to each channel. By default, it's set at 4, but I'm not sure what that means. Does that mean that each channel can at max have 4 clusters assigned to it?

(seems unlikely, I often get many clusters for a given channel):
![image](https://user-images.githubusercontent.com/3865975/55032527-6ca05f80-4fe7-11e9-9b12-0b3e9ea73314.png)

Otherwise, does this just limit the maximum number of clusters that KS will find to 4x the number of good channels? ie. if I had 32 channels, it can find, at most, 32x4 clusters?

**Comment by marius10p** [comment]
Your second interpretation is correct, and it only refers to clusters obtained in the main optimization, which is overmerged. before the final splits and merges. It is unlikely you will ever hit 4x so it should be a safe upper bound.

**Comment by angelonc** [comment]
Ok, the reason I was curious is that I sometimes see a large number of low spike count, low amplitude clusters on the same channel. My guess is that they are just noise, given how close they are to the noise floor, and some strangeness with the ACGs and CCGs. I'm trying to get a good sense of an amplitude cutoff for noise, but it seems to depend on the noise floor of each recording (or channel). Maybe a measure of SNR in addition/instead of the amplitude would be useful in phy.

![image](https://user-images.githubusercontent.com/3865975/55033525-c3a73400-4fe9-11e9-8b05-e949982ef5bc.png)
