### ISSUE TITLE
Can we stop plotting?

### ISSUE THREAD

**Issue by brendonw1** [MouseLand/Kilosort2#48]
The repeated plotting means I basically can't effecitively use other programs at the same time - typing in other program gets put into matlab whenever a matlab fig gets popped up, which then calls over the matlab mainwindow.  How can plotting be turned off or delayed until the end of the kilosort run?

**Comment by marius10p** [comment]
Sorry, I added ops.fig which you can set to 0 to not show figures in the main loop. It will still show the batch-to-batch distance matrix.

**Comment by brendonw1** [comment]
Thanks!

**Comment by brendonw1** [comment]
Related to this - is there a good way to save my own defaults that won't
get overwritten by git pulls?  I could come up with something, but didn't
know if there's already some way that is good?

B

**Comment by marius10p** [comment]
We recommend users to make a copy of master_file and the config file outside of the repository. You then need to change the paths in this new master_file to point to your new config_file where you keep your defaults.

**Comment by brendonw1** [comment]
Thank you
