### ISSUE TITLE
Kilosort 1 versus 2

### ISSUE THREAD

**Issue by barbouni** [MouseLand/Kilosort2#49]
Hello! We run kilosort 1 and kilosort 2 (using the default parameters) for the same data and we are getting significantly less clusters recognized from kilosort 2.  Any ideas why that might happen?
Thank you!

**Comment by marius10p** [comment]
Hey, one reason could be that it works better and gives you complete single neurons without needing to merge clusters in the Phy GUI, which is the reason Kilosort1 gave you so many clusters.  But are you saying that even after manual curation Kilosort2 gives you fewer well isolated single neurons?

**Comment by barbouni** [comment]
Thank you very much! No it gives pretty much the same number of single units and the spiketimes are more or less the same. So I guess it should be ok.

**Comment by marius10p** [comment]
Great! That means it works as intended, and it doesn't oversplit neurons as much as Kilosort1 did.

**Comment by dervinism** [comment]
In my case I get fewer clusters and spikes in clusters with KS2, 2.5, and 3 vs 1. Also clusters spread over fewer number of recording channels (distorted data). Could this be due to drift correction? How would one run kilosort 3 with drift correction disabled?
