### ISSUE TITLE
CAR computation in GUI includes dead channels

### ISSUE THREAD

**Issue by AurelieP23** [MouseLand/Kilosort2#50]
It seems that if running Kilosort2 via the GUI, common median referencing in ksFilter.m is computed with all channels as inputs, including dead channels. This is not the case when running KS2 via the command line. Can you confirm this is true? This can be a bit misleading when trying to probe whether KS2 works as expected using the GUI. 
Otherwise, KS2 works great, thank you!

**Comment by nsteinme** [comment]
Thanks, good point... it's not totally trivial to fix so I can't do it immediately. To clarify though: when you actually run KS2 in the GUI it should do things correctly (your output files and visualization in Phy should be fine) - it's only the visualization in the gui that is at fault. And, a somewhat obnoxious workaround is: define a channel map that doesn't have the noisy channels as part of it in the first place. I.e. if your current channel map is [1 2 3 4] but channel 2 is dead and getting dropped, just make a new channel map with [1 3 4] so ch 2 will be ignored from the start, including in the gui.

**Comment by AurelieP23** [comment]
Ok, thanks for confirming and clarifying!
