### ISSUE TITLE
A bug in preprocessDataSub?

### ISSUE THREAD

**Issue by HiroMiyawaki** [MouseLand/Kilosort2#53]
In the high pass filtering loop in preprocessDataSub.m, 
reading frame progresses by [NT-ops.ntbuff] sample points,
but [NT] sample points are written to temp_wh.dat,
so the filtered signal becomes longer than the original dat.

Is it intentional?
I thought it's a bug, but somehow final results seem fine.

**Comment by HiroMiyawaki** [comment]
I think it is intentional.
temp_wh.dat includes buffers used later in learnAndSolve8b.m. Right?

**Comment by marius10p** [comment]
Correct, it is intentional to reduce artifacts at transitions between batches.
