### ISSUE TITLE
Unclear error during automatic sorting

### ISSUE THREAD

**Issue by Ruairi-osul** [MouseLand/Kilosort2#55]
Hello, 

Kilosort2 has recently started throwing the following errors during main optimization. Has anyone else encountered this or can think of any posible causes?

![ksort2_error](https://user-images.githubusercontent.com/29435612/56424864-df7cbd80-62a9-11e9-8f5b-105c18def157.png)

There are no errors on the matlab command line.

It had previously been running fine on the same data format.

Data is from a 32 channel silicon probe sampled at 30 kHz.

**Comment by Ruairi-osul** [comment]
As an update: 

when I run kilosort2 using the scripts, I get variable responses using the same data and parameters.
On some runs, it works with no errors. 
On others, this message comes up:

![error_1](https://user-images.githubusercontent.com/29435612/56439764-3bae0480-62df-11e9-86c1-b9c53aef5263.png)

And on others, this one does:

![error2](https://user-images.githubusercontent.com/29435612/56439777-47013000-62df-11e9-83a8-cff99c60be17.png)

**Comment by NoahDolev** [comment]
Hi,

I think this may be related to issue #44 . If I close Matlab and re-open it - in some sessions it works and in some sessions it doesn't. So this error is just getting weirder the more I dig into it. 

Cheers,
Noah

**Comment by facazevedo** [comment]
The same happens to me.

**Comment by marius10p** [comment]
Could not reproduce error.  Might be due to empty batches, which should now be fixed.
