### ISSUE TITLE
Adding support for uint16 data?

### ISSUE THREAD

**Issue by jvoigts** [MouseLand/Kilosort2#57]
We're currently saving data in uint16 files because that's the native output from Intan chips. I assume this goes for many ADCs. Would it make sense to you guys to add an option to switch preprocessDataSub from assuming int16 to a uint16 with a (2^16)/2 offset? Looks to me like that would be a very easy addition?

We could of course patch our copy of kilosort, or (as we do now) just convert our files separately, but that seems messier than having a config flag for these cases.

**Comment by marius10p** [comment]
Old issue, but generally speaking I am happy to take in any pull requests.
