### ISSUE TITLE
settings

### ISSUE THREAD

**Issue by MarcelMB** [MouseLand/Kilosort2#61]
Hey,

I have a question regarding the settings. Is there any literature except the one paper and the wiki which dont (at least for me) really explain what the settings in the GUI excactly do? It is kind of hard to figure out how to change Threshold, Lambda and AUC for splits for different data type and if it is necessary to change other parameters as well.

I would appreciate help a lot. Thanks!

**Comment by marius10p** [comment]
Threshold and lambda work the same as in Kilosort1:
https://www.biorxiv.org/content/10.1101/061481v1

AUC for splits is an added step at the end which decides whether to split a cluster or not, if the split would look like a bimodal distribution with a discrimination between modes at least as good as the AUC parameter. For AUC of an ROC curve see here:

https://en.wikipedia.org/wiki/Receiver_operating_characteristic

![image](https://user-images.githubusercontent.com/3935246/57389711-c1a7c780-7188-11e9-9963-56376062a7a6.png)

**Comment by MarcelMB** [comment]
Thanks a lot!

I just discovered an issue while changing bad channels.

First, kilosort runs completely fine if I dont modify the bad channels.
If I change manually the bad channels after prepocessing it usually shows different error messages in the process of spikesorting. Can I manually choose which channels to use and to be consideres as good without the software changing it again?

**Comment by marius10p** [comment]
You can set minfr of bad channels to 0, and then all channels will be used. The default is:

ops.minfr_goodchannels = 0.1;

**Comment by MarcelMB** [comment]
Thank you for your help!

I discovered on more 'bug' with a dataset, where after preprocessing an error messages appears: "Error running kilosrt! Input matrix contains NaN or Inf." 

However the data is displayed completely fine. It found 13770 threshold corssings in 212 sesoncd of data
it found 4 bad channels

But it basically displays some warning messages like: 

  "In clusterSingleBatches (line 95)
  In ksGUI/runSpikesort (line 782)
  In ksGUI/runAll (line 628)
  In ksGUI>@(~,~)obj.runAll() (line 319) 
  Warning: data batch #3 only had 1 spike"

Its basically stops runnig after this:

"time 11.64, pre clustered 501 / 777 batches 
time 0.01, compared 1 / 777 batches 
time 2.74, compared 501 / 777 batches "

However I managed to run this excat dataset previosuly somehow but I cant remember how excatly I managed it.

**Comment by PhantomSpike** [comment]
Hi @marius10p ,

I think this is a related issue so I won't open a new one.

I am getting too many splits on my data (using Phase 3A). If I want to reduce the number of splits, should I simply increase the AUC value? What are reasonable values to play with?

Thanks!

**Comment by marius10p** [comment]
I guess you tried different values and found one that works well for you. This probably depends on recording configuration.
