### ISSUE TITLE
predicted data is flat

### ISSUE THREAD

**Issue by KacperKon** [MouseLand/Kilosort2#62]
Hi,
I've tried using Kilosort2 on my 8-tetrodes data and also the sample data from http://data.cortexlab.net/singlePhase3/data/. In both cases the predicted (blue) data traces in the GUI are totally flat (both raw and filtered data looks ok). I've double-checked the number of channels and it seems to be fine. After sorting all the clusters look like noise. Playing with parameters, restarting everything etc. doesn't help. Do you have any idea what might be the source of the problem?

**Comment by nsteinme** [comment]
Could you post a screenshot of the gui before you click 'run', for the
singlePhase3 dataset? And could you paste any output to the command window
that happens during execution? You are using the '*.ap.bin' file that is
81GB, right?

**Comment by Sepidak** [comment]
I have the same problem. Although, unlike Kacper, clusters look fine after sorting. I was also running kilosort2 before from the command line and was happy with the result, but only noticed this issue after switching to the GUI.  Here are a few screenshots from the GUI and then the result in phy, all done on the 81GB 'ap.bin' data file on the cortexlab site:

![Screenshot_2019-05-08_20-26-47](https://user-images.githubusercontent.com/28627358/57403167-ede73680-71d0-11e9-86d3-c3f9a3323cc8.png)

![Screenshot from 2019-05-08 20-27-56](https://user-images.githubusercontent.com/28627358/57404944-27ba3c00-71d5-11e9-9d92-8b84f9fd1dfc.png)

![Screenshot from 2019-05-08 20-28-24](https://user-images.githubusercontent.com/28627358/57408653-25101480-71de-11e9-90f5-05f71d75c9f0.png)

![Screenshot from 2019-05-08 22-10-21](https://user-images.githubusercontent.com/28627358/57408670-29d4c880-71de-11e9-8ad8-b681efd6844b.png)

![Screenshot from 2019-05-08 23-32-47](https://user-images.githubusercontent.com/28627358/57412740-acaf5080-71e9-11e9-82c0-5888fb726c44.png)

**Comment by KacperKon** [comment]
Thank you for the quick response. I've used the short sample file with raw data (rawDataSample.bin). I will get back to you when I run the analysis on the long one.

**Comment by KacperKon** [comment]
Thank you for your quick response. I've used the short sample file (rawDataSample.bin). I will get back to you when I run the analysis on the propper file.

**Comment by KacperKon** [comment]
So now it looks exactly like Sepidak described - on the right file the sorting works well, but the predicted data is flat. Actually there was a moment today when it started looking fine for a few minutes and then came back to flat line, even though I didn't do anything except from scrolling. So I guess this is only a display issue. 
![GUI_KS2](https://user-images.githubusercontent.com/45356822/57458964-93061b80-7272-11e9-97c2-900ac6a7ad14.png)

**Comment by marius10p** [comment]
Closed from inactivity,
