### ISSUE TITLE
Loading data into kilosort2

### ISSUE THREAD

**Issue by jofrony** [MouseLand/Kilosort2#64]
I have started using Kilosort2 for our Neuropixel data - which is saved in an OpenEphys format, where every channel is saved into a 'CH*.continuous format. I have used the openephys to convert this into a joint *.dat file (using openephys.pack() in python), which I am able to load and visualise in the GUI. The preprocessing works, as it has loaded all the channels and can process the data, but the spikesorting fails - due to there not being any spikes - error in Message Log is 'Error running kilosort! Input matrix contains NaN or inf'. This is obvious from looking at the filtered data which is completely flat. Hence, I am wondering if the filters are not suited for the data or that the file format is wrong.

**Comment by angelonc** [comment]
While the GUI may work in visualizing your data, make sure it is not spitting some sort of warning like 'Guessing that number of channels is %d. If it doesn't look right, consider trying: %s'. If it is, you may be giving it the wrong number of channels (this will usually happen to me if I accidentally record some of the analog channels in the openEphysGUI).

I'm not sure what the GUI does when there is a channel mismatch, as far as running Kilosort. But making absolutely sure that your channel count is correct is the first step I think. If you're sure of that, it could be that you have very few spikes in your recording, which will cause Kilosort to fail.

**Comment by marius10p** [comment]
Inactive, closing.
