### ISSUE TITLE
Sorting different .ap.bin files from same penetration together?

### ISSUE THREAD

**Issue by PhantomSpike** [MouseLand/Kilosort2#65]
Hi,

This is related to issue #37 but not quite the same.

Firstly, thanks to all the people involved in the development of this great software. It's really invaluable for the community!

I haven't tested very systematically but it seems that I loose clusters when I concatenate files. To be clear, the electrode is in exactly the same place and I am using SpikeGLX. I would record stimulus 1 for say 20 mins, then disable recording from SpikeGLX. I would then enable recording again and collect stimulus 2 and so on. I did a test with a simple stimulus where I get around 40 frequency tuned neurons. When I ran KS2 again with the same stimulus concatenated with other bin files from the same penetration, the  clusters dropped to only 20 tuned neurons and they looked worse. 

I wonder if concatenating files maybe introduced sudden jumps/discontinuities which throw off Kilosort2 drift correction algorithm? The algorithm assumes some reasonable degree of continuity which is violated at the junction points of the concatenated files?

If this is the case, which of the following 3 options would be best:

1. Record a continuous ap.bin file that has all the stimuli. Sort them all together with KS2 and split them post-hoc afterwards using the channel that collects the triggers (synch channel)

OR 

2. Record separately and concatenate. When concatenating, adjusts channel gains so that they are comparable across concatenated sessions. This might alleviate some of the discontinuity issues?

OR

3. Somehow apply the same spike templates from one recording session to the next. I think this is what user babaq (Li Alex Zhang) proposed. As far as I got, this is low on the priority list.

I raised similar issue on the Neuropixel's slack channel and this is what Bill Karsh (Creator of SpikeGLX) wrote:

"I will write a small help document on stitching for the SpikeGLX downloads page but for now, perhaps your discontinuity issue stems from this... Files recorded as individual trials, that is, sets of t-indices, are not typically contiguous so they can not simply be appended to each other. Rather, use the metadata file: 'firstSample' gives the index number of the first sample in the file. The sample rate you should consult is 'imSampRate'. The total length of the file in samples is 'fileSizeBytes/(2*nSavedChans)'.  These data tell you how IM files fit on the timeline. If two files overlap, you can select samples from either one because they will be identical samples drawn from the same underlying history stream. If there are gaps, you will have to decide how to fill with zeroes or some extrapolation that works best for your analysis needs. You should probably encourage the authors of your favorite spike sorters to import trial-based files automatically so you don't have to manually sew them together."

I am not sure what he means by "import trial-based files automatically so you don't have to manually sew them together". @marius10p @carsen-stringer would this be something that could be implemented?

Thanks!

**Comment by djoshea** [comment]
I'm interested in this because I've been concatenating multiple ap.bin files together and kilosorting the resultant without any trouble. I've also had one or two days where the gains differed across files and I multiplied the lower gain files to equalize the effective gain. My code at [djoshea.github.io/neuropixel-utils/](https://djoshea.github.io/neuropixel-utils/) does this automatically. 

Have you tried plotting the concatenated ap.bin file around the time of the concatenation to verify that there is a discontinuity? It's not immediately clear to me that introducing a DC jump across all channels would present an issue because of the additive assumptions used in the sorting algorithm and the common average referencing. 

Does Kilosort2's batch reordering plot suggest that the second file is very different from the first?

**Comment by etrautmann** [comment]
I believe the discontinuity is not a difference in DC offset, but rather
the jump between the last sample of recording 1 and the first sample of
recording 2. The HP filtering should take care of any DC offsets and the
high frequency artifact introduced by a single stitching hasn’t been an
issue for any of the stitched data I’ve tried as it’s unlikely to even
cross threshold and only occurs as a single event.

I’ve talked with at least one person who uses separate files for every
trial and is stitching hundreds of recordings together. My guess is that
this still works fine, but I haven’t yet tried this's.

**Comment by peterfschade** [comment]
I stitch together thousands of files (1-7s files) and will occasionally get clusters in the KS2 output that are clearly artifacts of the stitching ( a square step up or step down) with a number of 'spikes' approximately equal to the number of files.  I have not seen your issue yet but my ITI is in the range of a couple hundred ms and they look qualitatively similar to my longer recordings, but I only have few of these. What is the duration between your recordings? 

What is the minFR parameter in your Config file set to? It could be that a subset of the neurons like stimulus 1 but not stimulus 2 so the firing rate dips below threshold for too long and those neurons are removed. This could explain the drop in clusters when concatenating different stimulus blocks.

**Comment by marius10p** [comment]
Issue has become inactive. Closing.
