### ISSUE TITLE
Questions of using stereotrode to distinguish single unit

### ISSUE THREAD

**Issue by Gery111** [MouseLand/Kilosort2#68]
Dear all,

Many researches using tetrode to distinguish the single unit, and we want to use stereotrode (two channels as one group, not four channels ), because we only have 32-channel system and we want to record more neurons. If we use the eclectic methods, I am not sure whether what we get will be single-unit( or multi-unit?).

I am not familiar with the algorithm of spike-sorting, so I want to ask what are effective factor of spike-sorting. If the density of neurons in the brain area is high(e.g., hippocampus has high neuron-density), how are that results going? or if we record more signal( e.g., recording more time), will that be more precise spike-sorting?

Any help will be appreciative. We have made few DIY electrode with stereotrode, if that problem is serious, we will make tetrode next time.

Thanks!

Jichen

**Comment by marius10p** [comment]
It is highly recommended to use tetrodes for spike sorting quality, especially in hippocampus where the neuron density is high. Recording longer periods won't really help with spike sorting.

**Comment by Gery111** [comment]
> It is highly recommended to use tetrodes for spike sorting quality, especially in hippocampus where the neuron density is high. Recording longer periods won't really help with spike sorting. You will probably end up isolating more units than you would with similar TOTAL number of channels with stereotrodes.

Thank you, we're going to use tetrodes.
