### ISSUE TITLE
Getting error if simulate record-time is short

### ISSUE THREAD

**Issue by Gery111** [MouseLand/Kilosort2#70]
If one use `make_eMouseData_Drift` and set a short `t_record` (like 12s), one will get an error of `Index exceeds matrix dimension`. Because in function `learnAndSolve8b`, line 342, nKeep=20,  short time simulation do not has enough PCs of 20, then it gets error in `rez.U_a(:,:,j) = gather(A(:, 1:nKeep) * B(1:nKeep, 1:nKeep));`
The code is as:

```
nKeep = 20; % how many PCs to keep
rez.W_a = zeros(nt0 * Nrank, nKeep, Nfilt, 'single');
rez.W_b = zeros(nBatches, nKeep, Nfilt, 'single');
rez.U_a = zeros(Nchan* Nrank, nKeep, Nfilt, 'single');
rez.U_b = zeros(nBatches, nKeep, Nfilt, 'single');
for j = 1:Nfilt    
    WA = reshape(rez.WA(:, j, :, :), [], nBatches);
    WA = gpuArray(WA);
    [A, B, C] = svdecon(WA);
    rez.W_a(:,:,j) = gather(A(:, 1:nKeep) * B(1:nKeep, 1:nKeep));
    rez.W_b(:,:,j) = gather(C(:, 1:nKeep));

    UA = reshape(rez.UA(:, j, :, :), [], nBatches);
    UA = gpuArray(UA);
    [A, B, C] = svdecon(UA);
    rez.U_a(:,:,j) = gather(A(:, 1:nKeep) * B(1:nKeep, 1:nKeep));
    rez.U_b(:,:,j) = gather(C(:, 1:nKeep));
end

```
By the way, It seems to have a slower creating time of simulation than kilosort1.

**Comment by marius10p** [comment]
Just generate a longer recording, it is meant to be at least ~10-20 minutes.

It is indeed much slower because it needs to shit data, upsample and interpolate to create drift.
