### ISSUE TITLE
question on processing neuropixels 1.0 /p3B2 2-columns aligned probes

### ISSUE THREAD

**Issue by WeissShahaf** [MouseLand/Kilosort2#71]
i'm using neuropixels 1.0 probes with SpikeGLX.
the .bin files are 385 channels (384+1 sync channel).
how does kilosort2 deal with that?
it knows there are 385 not 384 channels in the data. should i make a custom channel config file with 385 channels and disable the last channel?
if so what variables should i include in the file to disconnect the last channel?

**Comment by nsteinme** [comment]
This is taken care of because the channel map file only specifies that
1:384 are part of the probe. As long as the total number of channels is
correctly specified as 385, then the data will be read correctly.
