### ISSUE TITLE
File Format

### ISSUE THREAD

**Issue by johnrachwan123** [MouseLand/Kilosort2#72]
My .bin file is a 2D array with dimensions of Nx61. The first column corresponds to the timestamps and the 60 remaining columns correspond to my 60 recording channels. Also, the recorded values are int32. My 3 questions are:

What should be the format of the file in Kilosort? Meaning, how should I reshape the array to obtain correct sorting?
Does my file have to be int16 or does int32 work as well?
What should the units of time and potential be?
Following is a sample of the first 3 columns of my file (First column contains the timestamps in microseconds, second and third columns contain the potential recorded on my first 2 channels in 10^-9 Volts)

0	-1966965	59605
100	536445	2861040
200	6258525	-1430520
300	-2741830	-4529980
400	-1966965	2682225
500	1192100	2324595
600	-2980250	1847755
700	1192100	178815
800	-2861040	-1668940
900	-1251705	774865

**Comment by marius10p** [comment]
Remove the timestamp column and then transpose. int16 only please.

**Comment by marius10p** [comment]
Issue has become inactive. Closing.
