### ISSUE TITLE
Error when using 'connected'

### ISSUE THREAD

**Issue by mmmorimoto** [MouseLand/Kilosort2#73]
Hi,
I was trying to use the 'connected' function to disable 16/32 channels.
First I noticed that 'connected' is commented out in <preprocessDataSub.m> line 48.
When I uncomment this and add 'connected' as output of <loadChanMap.m> and ran the whole process, I got an error at the end in <rezToPhy.m> line 66, that U and W are gpuArrays and cannot be converted to single.
Is disabling channels through 'connected' not supported in the current version?

**Comment by marius10p** [comment]
That line is only for keeping track of connected, it has no effect on the sorting. 

'connected' is now applied in loadChanMap.m, called on line 19. If you set connected to 0 for some channels, they should automatically be excluded from the 'chanMap'  output and ignored from then on.

**Comment by marius10p** [comment]
Issue has become inactive. Closing.
