### ISSUE TITLE
Cannot run Kilosort

### ISSUE THREAD

**Issue by kouichi-c-nakamura** [MouseLand/Kilosort2#81]
Hello,

I think I managed to install kilosort2 and at least Kilosort2 GUI launches fine by the the `kilosort` command.

Now I'm trying to get the first results using Kilosort2. Looking at this page, I saved 16 channel probe data into an array of int16; the rows of the array represent channels, while columns represent time points. Saved it using the following code:

```matlab
 fid = fopen(destfile,'w');
 fwrite(fid, dataInt16, 'int16');
 fclose(fid);

```

It seems all right to me, but when I select that `.bin` file from Kilosort2 GUI, Even after filling the "Number of channels" manually, the "Run All" button has been inactivated.

![Image010](https://user-images.githubusercontent.com/6400352/60444349-f24e2f80-9c14-11e9-9704-f41e77ddf382.png)

Can anybody suggest anything to fix this? Is there something I've been overlooking?

Best,
Kouichi

**Comment by nsteinme** [comment]
try re-selecting the probe layout using the dropdown? It should have filled
in the other parameters and shown you some data. If you didn't see that,
try resetting the gui and choosing everything again. Try looking at the
command line to see whether there was an error message that you could paste
here.

**Comment by kouichi-c-nakamura** [comment]
Thanks for your help. It's a really naive question, but does Kilosort2 work for a PC without GPU? I assumed it could also work on CPU, but maybe not?

**Comment by kouichi-c-nakamura** [comment]
I just found the answer here: #47

It's very clear NO.
