### ISSUE TITLE
What is template_features (rez.cProj) variable?

### ISSUE THREAD

**Issue by catubc** [MouseLand/Kilosort2#82]
Hi Marius.  We're trying to emulate Kilosort output files for Phy and Cyrille has suggested we get some info on this parameter from you.   Is it some sort of projection of a single spike onto its assigned template?  
Thanks,
Cat

**Comment by marius10p** [comment]
It's the projection of every spike on its top N best matching templates. It is however scaled according to the footnote on page 11 of the biorXiv paper.

**Comment by catubc** [comment]
Thanks, that's helpful.
