### ISSUE TITLE
semantics of GetWaveform

### ISSUE THREAD

**Issue by skjenks** [MouseLand/Kilosort2#86]
@nsteinme  (or anyone else)
Hi, 
I currently trying to do offline spike sorting using kilosort. Currently, I am using the getWaveForms function (https://github.com/cortex-lab/spikes/blob/master/analysis/getWaveForms.m) in order to reorganize my data for further analysis. My questions are:

1) in line 12 it is commented : % Data.type of .dat file (this should be BP filtered).  Does this mean that the data has already been BP filtered or does it still need to be filtered?
 a) if it needs to be filtered how would I go about doing that ?

2) what is the temp_wh.dat file/should I use it for spike sorting instead of the raw data?

Thank you in advance!

**Comment by marius10p** [comment]
temp_wh.dat is a path you should give Kilosort2 as a temporary file. It needs to be the size of the data. 

I don't know about the other one.

**Comment by marius10p** [comment]
Issue has become inactive. Closing.
