### ISSUE TITLE
Kcoords not correctly transferred from GUI config to GUI/Kilosort2

### ISSUE THREAD

**Issue by DJ-Hayden** [MouseLand/Kilosort2#88]
Hello!

When running a 2-shank probe, the GUI and resulting file in Kilosort2-master/configFiles correctly show/indicate a 2-shank connection. One shank is 1 and the other is 2.

However, the GUI appears to ignore this completely (only shows 1 shank, albeit in the correct orientation) and the resulting dataset's rez.ops.kcoords sets everything to 1. Surprisingly, everything works just fine regardless (albeit with some weird plotting errors and data warnings from time to time). I haven't extracted the isolated spikes myself yet, but I'm sure that will be illuminating. 

In the meantime, I'll just separate data into the different shanks. I'll also debug myself after a few weeks when things settle down.

Thanks!

**Comment by marius10p** [comment]
There is no option to separate shanks in Kilosort2, but you don't really need to do that anymore. Just give them offset X coordinates: a spike will only be extracted from a local neighborhood.

**Comment by marius10p** [comment]
Issue has become inactive. Closing.
