### ISSUE TITLE
gpuArray memory access issue in `learnAndSolve8b`

### ISSUE THREAD

**Issue by siaahmadi** [MouseLand/Kilosort2#91]
In line 203 of `learnAndSolve8b.m`:
`W(:,Nfilt + [1:size(dWU0,3)],:) = W0(:,ones(1,size(dWU0,3)),:);`
accessing W0 as follows
`W0(:, [1, 1], :)`
produces the following error:
> Error using gpuArray/subsref
> An unexpected error occurred trying to launch a kernel. The CUDA error was:
> invalid configuration argument

Running the subsref access code immediately after line 73 where `W0` is initialized (`W0 = permute(double(wPCA), [1 3 2]);`) or running it for a second time right before line 203 (mentioned above) will not produce any errors.

Can somebody please help.

**Comment by marius10p** [comment]
how many channels do you have?

**Comment by siaahmadi** [comment]
> how many channels do you have?

I'm working with tetrodes. I have combined four tetrodes for a total of 16 channels in one file.

How does the number of channels play a role here?

**Comment by marius10p** [comment]
Re-open if this is still a problem. Sometimes CUDA code in Matlab fails for weird reasons.
