### ISSUE TITLE
GUI: Spikesorting of Neuropixels Sample Data Fails

### ISSUE THREAD

**Issue by AGenews** [MouseLand/Kilosort2#92]
Dear Folks,
first of all, thanks for this great piece of software!

However, I have some problems running KiloSort2 on the admittedly huge sample data set _Hopkins_20160722_g0_t0.imec.ap_CAR.bin_ from UCL found [here](http://data.cortexlab.net/singlePhase3/data/).

**My system:**
Windows 10 Education, Intel i7-8700K, MATLAB 2016b, CUDA 7.5, GeForce RTX2080, 32GB RAM

I am using the GUI and the preprocessing works fine, however after ~10 min of spikesorting it fails telling me:
`Error running kilosort! Undefined function 'zscore' for input arguments of type 'gpuArray'.`

I hope this is not MATLAB 2016b related ... 

Yours sincerely and many thanks!
Andreas

**UPDATE:**
... so I've just tested my install with the "not-drifting" sample data `sim_binary.dat` generated by KiloSort1 `master_eMouse.m` and this works nicely with KiloSort2!
I'll try to get the drifting version to run ....

**Comment by nsteinme** [comment]
I think you need "statistics & machine learning" toolbox, and parallel
computing toolbox.
https://www.mathworks.com/help/stats/zscore.html

**Comment by AGenews** [comment]
Dear Nick,
thank' lot for the quick reply! Indeed I had to install the "statistics & machine learning" toolbox for the eMouse simulation, and running Kilosort2 with the `master_kilosort.m` works nicely now.
However, the GUI still fails in part, but now with a different error:
`Error saving data for phy! Reference to non-existent field 'Wphy'.`

Yours sincerely and many thanks,
Andreas

**Comment by KBillel** [comment]
Hi I think it's because you need to have the folder npy-matlab-master in your path. You can find it here : https://github.com/kwikteam/npy-matlab

**Comment by xintangg** [comment]
Hi

Have you solved this problem?

**Comment by AGenews** [comment]
Hi there ...
well I had all the respective software packages installed all along, so I figured I simply use the matlab script which works nicely. But with the GUI it didn't work and I haven't tried since then. 
Best,
A.

**Comment by marius10p** [comment]
My guess is that 2016b does not support z-score on the GPU, which the GUI uses but not the main code. You could write a little z-score function of your own and replace it in the code? I'd be happy to check any pull requests on this.

**Comment by jvschweim** [comment]
> Dear Nick,
> thank' lot for the quick reply! Indeed I had to install the "statistics & machine learning" toolbox for the eMouse simulation, and running Kilosort2 with the master_kilosort.m works nicely now.
> However, the GUI still fails in part, but now with a different error:
**> Error saving data for phy! Reference to non-existent field 'Wphy'.**
> Yours sincerely and many thanks,
> Andreas

On that issue, I sometimes get the same error message when I run kilosort2 on several files after each other. Clearing the .phy folder usually helps to get around the issue.

**Comment by erc84** [comment]
I'm also receiving the same error when using the GUI. I've made sure to add the npy-matlab-master folder to the path, have all the toolboxes otherwise properly installed, and I at least don't see any .phy folder in the kilosort directory to clear or modify. I'm also running R2019a. Any other suggestions?

**Comment by nsteinme** [comment]
This is an error that happens in the saving step *when a previous step has
failed to complete*. You can look in the status bar at the bottom of the
GUI for more information about what went wrong at the previous step.
