### ISSUE TITLE
Input data contains NaN and Inf Error

### ISSUE THREAD

**Issue by sandraromerop** [MouseLand/Kilosort2#96]
Hi all

I'm trying to set up Kilosort2 , using datasets from Neuralynx

My device is :  using  GeForce GTX 1060 , Matlab 2019a, Windows 10
[testCSCFile.zip](https://github.com/MouseLand/Kilosort2/files/3468562/testCSCFile.zip)
 64 bit, and Microsoft Visual C++ 2017. 

Until now I've come to this point:
- I've  managed to run the e-Mouse data drift sample data/code and it went through.
- I loaded the  data from .CSC files from Neuralynx to matlab-- writing them as int16 (I sort of played with the read/write  functions, see code below as don't know if it's accurate) 
- When loading the dataset to the gui   I see the traces and the spikes look ok by eye. 
- Preprocessing went through ok

Now the error comes when I run the spike sorting : 
- During the spike sorting I get some warnings : 'Warning: data batch #33 only had 12 spikes' and then  I get the error 'Error running Kilosort! Input matrix contains NaN or Inf '

Do you if that's caused by  the input data format or by the sparsity in the spikes of the recording? or neither. ? 

I attached the  channel ap files and the code I'm  using to write the int16 format .dat file 

thanks!!!!!
[testCSCFile.zip](https://github.com/MouseLand/Kilosort2/files/3468563/testCSCFile.zip)

**Comment by marius10p** [comment]
Can you please check your data in the Matlab GUI? Does it look like it was loaded correctly (i.e. the channels are contiguous and in the right order). Kilosort2 only sees the "filtered" version of the data which you can see in the GUI by pressing 2.

**Comment by marius10p** [comment]
Issue has become inactive. Closing.
