### ISSUE TITLE
Coordinates for electrodes in 3-Dimensions

### ISSUE THREAD

**Issue by djsoper** [MouseLand/Kilosort2#98]
I'd like to start by thanking the Kilosort team for their hard work. Sorting seemed an insurmountable task for the amount of data we have until I discovered Kilosort. 

My question is: how might one best sort an electrode(in this case a shank) whose contacts extend into three dimensions? I'm using a shank micro-macro electrode with macros along the length, and 4 radially-oriented micros between each macro. Only the micros record at 30k, so disregard the macros for coordinate creation. The only way I can think to do it with the 2D planar method is to have two planes intersecting perpendicular to each other, with opposing sides of the depth being on the same plane. I would lose a lot of important unit information though, because if the two adjacent contacts on one level of the micros recorded the same thing, I would not easily see how that unit propagated. Am I coming at the problem the right way? I'm hoping I'm missing something big here. The diameter of the shank is ~1.5mm, so the adjacent contacts a quarter turn away should be just shy of that distance apart. I think that these might possibly (though unlikely) pick up the same unit's activity. Any suggestions?

Thanks,
 DJS

**Comment by marius10p** [comment]
I don't think there is an easy way to do that, and it seems like an usual situation (I still can't picture it in my head). You could cluster the two planes separately, compare clusters, and remove any duplicates that have coincident spikes.

**Comment by marius10p** [comment]
Closed due to lack of activity.
