### ISSUE TITLE
Advanced options

### ISSUE THREAD

**Issue by Alkohost** [MouseLand/Kilosort2#99]
Can you please add an ability to edit main config file and advanced options directly from the GUI?

**Comment by nsteinme** [comment]
Hi, it's on the list that I hope to implement at some point. A sensible PR to implement this would certainly be welcome. In the meantime, you saw the workaround right, where you can edit the settings at the command line?

**Comment by Alkohost** [comment]
Thank you.
I think would be nice to have a field for a config file (it seems current default config is configFile384.m)
Sure, I saw the workaround, but I guess some of parameters like ops.fig should be 0 out of the box.
What to do if I need 5-10 clusters instead of 72 ?

**Comment by nsteinme** [comment]
There is no way to set a fixed number of clusters - automatic methods
determine an optimal number of clusters.
